import { Comparison } from "@/types/content";

export const comparisons: Comparison[] = [
  {
    slug: "plato-aristotle",
    leftThinkerSlug: "plato",
    rightThinkerSlug: "aristotle",
    titleJa: "イデア論 vs 実体論",
    subtitle: "理想から世界を見るか、個物から見るか。",
    themeSlugs: ["knowledge", "truth", "justice"],
    whyThisComparisonMatters: "西洋哲学の基礎的な分岐を最短でつかめる。",
    whatToWatch: ["本質の場所", "認識の起点", "政治秩序の設計"],
    summaryDifference: "プラトンは超越的普遍を、アリストテレスは内在的本質を重視。",
    commonGround: "両者とも理性的探究によってより良い生を目指した。",
    sections: [
      { title: "本質はどこにあるか", leftView: "イデア界に真の実在がある。", rightView: "個物の中に実体としてある。", takeaway: "超越と内在の対比。" },
      { title: "知の獲得", leftView: "想起と弁証法。", rightView: "観察と分類。", takeaway: "方法論の差が学問観を分ける。" },
    ],
    nextThinkerSlugs: ["aristotle", "zeno", "epicurus"],
    nextComparisonSlugs: ["aristotle-stoicism", "plato-epicurus"],
    nextThemeSlugs: ["knowledge", "happiness"],
  },
  {
    slug: "stoicism-epicureanism",
    leftThinkerSlug: "zeno",
    rightThinkerSlug: "epicurus",
    titleJa: "ストア派 vs エピクロス派",
    subtitle: "理性の徳か、静かな快か。",
    themeSlugs: ["happiness", "freedom", "human-nature"],
    whyThisComparisonMatters: "古代倫理の二大ルートを最短で比較でき、初学者の入口として機能する。",
    whatToWatch: ["幸福の定義", "感情との付き合い方", "社会参加の姿勢"],
    summaryDifference: "ストア派は徳と理性の一致を、エピクロス派は不安の除去と節度ある快を重視。",
    commonGround: "どちらも過剰欲望を抑え、心の平静を目指す実践哲学である。",
    sections: [
      { title: "幸福の基準", leftView: "徳それ自体が善で、外的条件は二次的。", rightView: "苦痛と不安の少ない安定した快が善。", takeaway: "善の中心が徳か快かで分かれる。" },
      { title: "自由", leftView: "判断を鍛え、外的変動に支配されない。", rightView: "不要な欲望と恐怖から離れて自足する。", takeaway: "内的統御と欲望調整の違い。" },
    ],
    nextThinkerSlugs: ["epictetus", "marcus-aurelius", "aristotle"],
    nextComparisonSlugs: ["epictetus-epicurus", "marcus-epictetus", "aristotle-stoicism"],
    nextThemeSlugs: ["happiness", "freedom"],
  },
  {
    slug: "aristotle-stoicism",
    leftThinkerSlug: "aristotle",
    rightThinkerSlug: "zeno",
    titleJa: "アリストテレス vs ストア派",
    subtitle: "共同体で徳を育てるか、理性で内的自足を作るか。",
    themeSlugs: ["happiness", "human-nature", "freedom"],
    whyThisComparisonMatters: "徳倫理の内部差を捉え、共同体倫理と内面倫理の重心差を理解できる。",
    whatToWatch: ["徳の形成方法", "外的善の評価", "共同体との関係"],
    summaryDifference: "アリストテレスは習慣と共同体、ストア派は理性と自然への同意を重視。",
    commonGround: "双方とも衝動任せでなく、訓練された実践を善い生の条件とする。",
    sections: [
      { title: "徳の育て方", leftView: "習慣と教育で中庸を体得する。", rightView: "判断訓練で自然に合致した理性を保つ。", takeaway: "共同体訓練と内面訓練の違い。" },
      { title: "外的条件", leftView: "ある程度の外的善は幸福に必要。", rightView: "外的条件は本質的善悪ではない。", takeaway: "幸福における外的要素の重みが異なる。" },
    ],
    nextThinkerSlugs: ["epictetus", "marcus-aurelius", "plato"],
    nextComparisonSlugs: ["stoicism-epicureanism", "marcus-epictetus", "plato-epicurus"],
    nextThemeSlugs: ["happiness", "human-nature"],
  },
  {
    slug: "plato-epicurus",
    leftThinkerSlug: "plato",
    rightThinkerSlug: "epicurus",
    titleJa: "プラトン vs エピクロス",
    subtitle: "理想秩序を求めるか、静かな日常を整えるか。",
    themeSlugs: ["happiness", "human-nature", "truth"],
    whyThisComparisonMatters: "理想国家型の倫理と日常実践型の倫理の差を初心者にも掴みやすく示せる。",
    whatToWatch: ["善のイメージ", "欲望への態度", "哲学の役割"],
    summaryDifference: "プラトンは魂秩序とイデア的善、エピクロスは恐怖除去と平静な快を重視。",
    commonGround: "両者とも快楽追従の生を批判し、節度ある生を求める。",
    sections: [
      { title: "善く生きる形", leftView: "魂の秩序化と真理志向で善に向かう。", rightView: "欲望を選別し不安を減らして安定した快を保つ。", takeaway: "上向き秩序化と静かな最適化。" },
      { title: "社会との距離", leftView: "政治秩序と教育設計を重視。", rightView: "小さな共同体で穏やかな生活を重視。", takeaway: "公的設計と私的実践の比重差。" },
    ],
    nextThinkerSlugs: ["aristotle", "zeno", "epictetus"],
    nextComparisonSlugs: ["aristotle-stoicism", "stoicism-epicureanism", "epictetus-epicurus"],
    nextThemeSlugs: ["happiness", "human-nature"],
  },
  {
    slug: "epictetus-epicurus",
    leftThinkerSlug: "epictetus",
    rightThinkerSlug: "epicurus",
    titleJa: "エピクテトス vs エピクロス",
    subtitle: "判断を鍛えるか、欲望を選ぶか。",
    themeSlugs: ["freedom", "happiness", "human-nature"],
    whyThisComparisonMatters: "実践哲学としての古代倫理を、日常レベルで比較できる。",
    whatToWatch: ["不安への対処", "訓練法", "快楽の位置づけ"],
    summaryDifference: "エピクテトスは判断統御、エピクロスは欲望調整と恐怖除去を重視。",
    commonGround: "どちらも外的成功より心の安定を優先する。",
    sections: [
      { title: "訓練の中心", leftView: "統御可能な判断と意志を反復訓練する。", rightView: "必要欲望に絞り、無用な不安源を減らす。", takeaway: "内面規律と生活設計の違い。" },
      { title: "自由理解", leftView: "外部に左右されない判断の自律。", rightView: "恐怖や過剰欲望からの解放。", takeaway: "自由の対象が判断か欲望かで異なる。" },
    ],
    nextThinkerSlugs: ["marcus-aurelius", "zeno"],
    nextComparisonSlugs: ["marcus-epictetus", "stoicism-epicureanism"],
    nextThemeSlugs: ["freedom", "happiness"],
  },
  {
    slug: "marcus-epictetus",
    leftThinkerSlug: "marcus-aurelius",
    rightThinkerSlug: "epictetus",
    titleJa: "マルクス・アウレリウス vs エピクテトス",
    subtitle: "統治の実践か、訓練の原則か。",
    themeSlugs: ["freedom", "happiness", "human-nature"],
    whyThisComparisonMatters: "ストア派内部の濃淡を示し、理論から実践への橋をつくれる。",
    whatToWatch: ["実践の場", "共同体責任", "自己訓練の語り口"],
    summaryDifference: "マルクスは公的責務下の省察、エピクテトスは普遍的訓練原則を前面化。",
    commonGround: "双方とも判断の規律を通じ、外的状況に振り回されない自由を目指す。",
    sections: [
      { title: "実践の文脈", leftView: "皇帝として責務を担いながら自己統御を試みる。", rightView: "教える立場から訓練原理を明確化する。", takeaway: "統治現場と教育現場の差。" },
      { title: "他者との関係", leftView: "共同体秩序に奉仕する徳を強調。", rightView: "個人の判断鍛錬から普遍倫理へ接続。", takeaway: "公共責任と個人訓練の焦点差。" },
    ],
    nextThinkerSlugs: ["zeno", "aristotle"],
    nextComparisonSlugs: ["stoicism-epicureanism", "aristotle-stoicism"],
    nextThemeSlugs: ["freedom", "human-nature"],
  },
  {
    slug: "descartes-hume",
    leftThinkerSlug: "descartes",
    rightThinkerSlug: "hume",
    titleJa: "合理主義 vs 経験主義",
    subtitle: "確実性は理性か経験か。",
    themeSlugs: ["knowledge", "truth", "language"],
    whyThisComparisonMatters: "カントへ向かう近代認識論の核心を短く理解できる。",
    whatToWatch: ["知識の源泉", "因果の正当化", "自我の確実性"],
    summaryDifference: "デカルトは理性の明証性、ヒュームは経験の習慣性を重視。",
    commonGround: "両者とも確実な知の条件を厳密に問うた。",
    sections: [
      { title: "知識の基礎", leftView: "コギトと生得観念。", rightView: "印象と観念の連合。", takeaway: "確実性の定義が異なる。" },
      { title: "因果", leftView: "理性で必然を捉える。", rightView: "必然は経験的習慣。", takeaway: "科学観と懐疑の温度差。" },
    ],
    nextThinkerSlugs: ["locke", "kant"],
    nextComparisonSlugs: ["descartes-locke", "locke-hume", "hume-kant"],
    nextThemeSlugs: ["knowledge", "truth"],
  },
  {
    slug: "descartes-locke",
    leftThinkerSlug: "descartes",
    rightThinkerSlug: "locke",
    titleJa: "デカルト vs ロック",
    subtitle: "知の出発点は理性か経験か。",
    themeSlugs: ["knowledge", "truth"],
    whyThisComparisonMatters: "近代認識論への最短入口として、合理論と経験論の分岐を明確に示す。",
    whatToWatch: ["生得観念の有無", "確実性の定義", "主体の役割"],
    summaryDifference: "デカルトは理性の明証を基礎にし、ロックは経験由来の観念分析を基礎にする。",
    commonGround: "どちらも独断を避けるため、知識の成立条件を丁寧に限定しようとした。",
    sections: [
      { title: "認識の起点", leftView: "コギトと生得観念を出発点にする。", rightView: "感覚と反省の経験から観念を組み立てる。", takeaway: "起点の差が知識観を分ける。" },
      { title: "真理の担保", leftView: "明晰判明な観念を理性で保証する。", rightView: "観念間の一致範囲を限定して真理を語る。", takeaway: "保証モデルと限定モデルの違い。" },
    ],
    nextThinkerSlugs: ["spinoza", "leibniz", "hume"],
    nextComparisonSlugs: ["spinoza-descartes", "leibniz-locke", "locke-hume"],
    nextThemeSlugs: ["knowledge", "truth"],
  },
  {
    slug: "spinoza-descartes",
    leftThinkerSlug: "spinoza",
    rightThinkerSlug: "descartes",
    titleJa: "スピノザ vs デカルト",
    subtitle: "合理論は二元論に留まるか、一元論へ進むか。",
    themeSlugs: ["knowledge", "truth", "freedom"],
    whyThisComparisonMatters: "同じ合理論でも、神・自然・主体の整理がどこまで変わるかを見通せる。",
    whatToWatch: ["実体の数", "心身関係", "自由の定義"],
    summaryDifference: "デカルトは心身二元論、スピノザは神即自然の一元論へ進む。",
    commonGround: "双方とも数学的明晰さで哲学を再建しようとした。",
    sections: [
      { title: "世界の基本構造", leftView: "神・精神・身体を一実体の様態として統一。", rightView: "精神と身体を異なる実体として区別。", takeaway: "一元化か二元化かで体系が変わる。" },
      { title: "自由", leftView: "必然理解を通じた能動化。", rightView: "理性主体の判断による自由。", takeaway: "自由の重心が異なる。" },
    ],
    nextThinkerSlugs: ["locke", "leibniz", "kant"],
    nextComparisonSlugs: ["descartes-locke", "leibniz-locke"],
    nextThemeSlugs: ["truth", "knowledge"],
  },
  {
    slug: "leibniz-locke",
    leftThinkerSlug: "leibniz",
    rightThinkerSlug: "locke",
    titleJa: "ライプニッツ vs ロック",
    subtitle: "精神は白紙か、内的構造をもつか。",
    themeSlugs: ["knowledge", "truth"],
    whyThisComparisonMatters: "生得的構造と経験起点の対立を、近代認識論のど真ん中で比較できる。",
    whatToWatch: ["生得観念", "必然真理の扱い", "経験の役割"],
    summaryDifference: "ライプニッツは生得的原理を擁護し、ロックは経験的形成を強調する。",
    commonGround: "両者とも知識の範囲を明確にし、混乱した形而上学を整理しようとした。",
    sections: [
      { title: "生得性", leftView: "精神には潜在的原理が備わる。", rightView: "観念は経験から生じる。", takeaway: "潜在構造の有無が核心。" },
      { title: "真理", leftView: "必然真理は理性内の原理で説明できる。", rightView: "真理は観念の一致関係として段階的に捉える。", takeaway: "真理の成立条件が異なる。" },
    ],
    nextThinkerSlugs: ["hume", "kant"],
    nextComparisonSlugs: ["locke-hume", "hume-kant"],
    nextThemeSlugs: ["knowledge", "truth"],
  },
  {
    slug: "locke-hume",
    leftThinkerSlug: "locke",
    rightThinkerSlug: "hume",
    titleJa: "ロック vs ヒューム",
    subtitle: "経験論はどこまで懐疑を進めるか。",
    themeSlugs: ["knowledge", "truth"],
    whyThisComparisonMatters: "経験論内部の温度差を押さえると、カントの問題設定が読みやすくなる。",
    whatToWatch: ["因果の扱い", "自我観", "知識の確実性"],
    summaryDifference: "ロックは経験論を穏健に運用し、ヒュームは因果と自己に懐疑を深める。",
    commonGround: "どちらも経験を認識の現場として重視する。",
    sections: [
      { title: "経験の使い方", leftView: "経験を通じた観念整理で知識を積み上げる。", rightView: "経験は習慣連合に留まり、必然は保証できない。", takeaway: "穏健経験論と懐疑的経験論の差。" },
      { title: "主体", leftView: "同一的自己を前提に議論を進める。", rightView: "自己は印象束として記述される。", takeaway: "自己の安定性評価が異なる。" },
    ],
    nextThinkerSlugs: ["kant", "berkeley"],
    nextComparisonSlugs: ["hume-kant", "berkeley-locke"],
    nextThemeSlugs: ["knowledge", "truth"],
  },
  {
    slug: "berkeley-locke",
    leftThinkerSlug: "berkeley",
    rightThinkerSlug: "locke",
    titleJa: "バークリー vs ロック",
    subtitle: "経験論は物質実体を必要とするか。",
    themeSlugs: ["knowledge", "truth"],
    whyThisComparisonMatters: "経験論が観念論へ傾く分岐を短く理解でき、ヒュームへの橋も見える。",
    whatToWatch: ["物質実体", "知覚の地位", "外界の確実性"],
    summaryDifference: "ロックは物質実体を残し、バークリーは知覚と精神だけで世界を説明する。",
    commonGround: "両者とも経験を出発点にし、抽象的実体概念を警戒する。",
    sections: [
      { title: "外界", leftView: "外界は知覚される観念と精神で捉える。", rightView: "一次性質を支える物質基体を想定する。", takeaway: "実体仮説を残すか切るか。" },
      { title: "確実性", leftView: "神の秩序で知覚世界の連続性を確保。", rightView: "経験的一致から外界の確からしさを確保。", takeaway: "保証装置の違い。" },
    ],
    nextThinkerSlugs: ["hume", "kant"],
    nextComparisonSlugs: ["locke-hume", "hume-kant"],
    nextThemeSlugs: ["knowledge", "truth"],
  },
  {
    slug: "hume-kant",
    leftThinkerSlug: "hume",
    rightThinkerSlug: "kant",
    titleJa: "懐疑から批判へ",
    subtitle: "経験の限界をどう超えるか。",
    themeSlugs: ["knowledge", "truth", "freedom"],
    whyThisComparisonMatters: "近代哲学の転回点をつかむ。",
    whatToWatch: ["先験的条件", "因果の地位", "道徳の根拠"],
    summaryDifference: "ヒュームは正当化の縮減、カントは条件の再構成。",
    commonGround: "双方とも独断を避け、認識の限界を重視した。",
    sections: [
      { title: "経験の位置づけ", leftView: "経験は習慣の束。", rightView: "経験は先験的形式で成立。", takeaway: "限界論から構成論へ。" },
      { title: "道徳", leftView: "感情を中心に説明。", rightView: "理性の自律で基礎づけ。", takeaway: "倫理の重心が移る。" },
    ],
    nextThinkerSlugs: ["kant", "bentham"],
    nextComparisonSlugs: ["kant-bentham"],
    nextThemeSlugs: ["freedom", "truth", "happiness"],
  },
  {
    slug: "kant-bentham",
    leftThinkerSlug: "kant",
    rightThinkerSlug: "bentham",
    titleJa: "カント vs ベンサム",
    subtitle: "行為は原理で裁くか、結果で裁くか。",
    themeSlugs: ["happiness", "justice", "state-legitimacy"],
    whyThisComparisonMatters: "義務論と功利主義の分岐を押さえると、近代倫理の読み方が一気に整理できる。",
    whatToWatch: ["行為評価の基準", "人格の位置づけ", "制度設計への接続"],
    summaryDifference: "カントは普遍化可能な原理を、ベンサムは結果効用の総量を基準にする。",
    commonGround: "どちらも恣意的道徳や慣習依存を越える、公共的判断基準を求めた。",
    sections: [
      { title: "善悪判定", leftView: "動機と原理が普遍化できるかで判断。", rightView: "結果として幸福がどれだけ増えたかで判断。", takeaway: "原理先行か結果先行か。" },
      { title: "政治と法", leftView: "人格尊重を侵す政策は許されにくい。", rightView: "全体効用を増やすなら制度改革を積極化できる。", takeaway: "権利保護の強さと政策柔軟性の差。" },
    ],
    nextThinkerSlugs: ["mill", "rawls"],
    nextComparisonSlugs: ["bentham-mill", "rawls-marx"],
    nextThemeSlugs: ["happiness", "justice"],
  },
  {
    slug: "bentham-mill",
    leftThinkerSlug: "bentham",
    rightThinkerSlug: "mill",
    titleJa: "ベンサム vs ミル",
    subtitle: "功利主義は量だけでよいのか、質も要るのか。",
    themeSlugs: ["happiness", "freedom", "state-legitimacy"],
    whyThisComparisonMatters: "同じ功利主義内部の差を押さえることで、自由主義政策との接続が見えやすくなる。",
    whatToWatch: ["幸福の測り方", "自由の位置づけ", "多数者支配の危険"],
    summaryDifference: "ベンサムは量的効用を、ミルは質的差異と自由原理を重視する。",
    commonGround: "どちらも道徳と政策判断を社会的帰結に接続しようとした。",
    sections: [
      { title: "幸福概念", leftView: "快苦は原理的に同一尺度で比較できる。", rightView: "高次の快を区別し、人格発達を評価に入れる。", takeaway: "量的功利主義と質的功利主義。" },
      { title: "自由", leftView: "自由は効用最大化の手段として扱われやすい。", rightView: "危害原理により自由を制度的に強く守る。", takeaway: "自由の独立価値をどこまで認めるか。" },
    ],
    nextThinkerSlugs: ["rawls", "rousseau"],
    nextComparisonSlugs: ["rawls-marx", "locke-rousseau"],
    nextThemeSlugs: ["freedom", "happiness"],
  },
  {
    slug: "hobbes-locke",
    leftThinkerSlug: "hobbes",
    rightThinkerSlug: "locke",
    titleJa: "ホッブズ vs ロック",
    subtitle: "国家は秩序の防壁か、権利保護の装置か。",
    themeSlugs: ["state-legitimacy", "freedom", "justice"],
    whyThisComparisonMatters: "近代国家の正当性を、主権集中モデルと権利保障モデルで対照できる。",
    whatToWatch: ["自然状態像", "契約の目的", "抵抗権の有無"],
    summaryDifference: "ホッブズは安全確保のため強主権を、ロックは権利保護のため限定政府を重視。",
    commonGround: "どちらも政治権力の正当化を神学ではなく契約論で説明した。",
    sections: [
      { title: "国家の役割", leftView: "内戦回避のため秩序維持を最優先する。", rightView: "生命・自由・財産の保護に国家を限定する。", takeaway: "秩序優先か権利優先か。" },
      { title: "市民の位置", leftView: "主権への服従が安定の条件になる。", rightView: "政府が契約を破れば抵抗の正当化が可能。", takeaway: "服従モデルと条件付き委任モデルの差。" },
    ],
    nextThinkerSlugs: ["rousseau", "mill"],
    nextComparisonSlugs: ["locke-rousseau", "bentham-mill"],
    nextThemeSlugs: ["state-legitimacy", "freedom"],
  },
  {
    slug: "locke-rousseau",
    leftThinkerSlug: "locke",
    rightThinkerSlug: "rousseau",
    titleJa: "ロック vs ルソー",
    subtitle: "自由は権利保護か、共同自己統治か。",
    themeSlugs: ["freedom", "state-legitimacy", "justice"],
    whyThisComparisonMatters: "自由主義と共和主義の分岐を短く比較でき、現代民主主義の論点に直結する。",
    whatToWatch: ["自由概念", "主権の担い手", "不平等への態度"],
    summaryDifference: "ロックは個人権利中心、ルソーは一般意志への参与を自由の核に置く。",
    commonGround: "どちらも統治の正当性を被治者の同意から導こうとした。",
    sections: [
      { title: "自由", leftView: "私的領域を守る消極的自由を重視。", rightView: "共同立法に参与する市民的自由を重視。", takeaway: "保護される自由と実践する自由。" },
      { title: "共同体", leftView: "多様な利害を調整する限定政府。", rightView: "平等な市民の一般意志で共同体を構成。", takeaway: "権力抑制と市民統合の軸差。" },
    ],
    nextThinkerSlugs: ["rawls", "marx"],
    nextComparisonSlugs: ["rawls-marx", "hobbes-rousseau"],
    nextThemeSlugs: ["freedom", "state-legitimacy", "justice"],
  },
  {
    slug: "rawls-marx",
    leftThinkerSlug: "rawls",
    rightThinkerSlug: "marx",
    titleJa: "ロールズ vs マルクス",
    subtitle: "不平等は再配分で是正できるか、構造転換が必要か。",
    themeSlugs: ["justice", "state-legitimacy", "freedom"],
    whyThisComparisonMatters: "現代の格差論争を、制度内改革と構造批判の二路線で比較できる。",
    whatToWatch: ["不平等の原因", "正義原理", "国家の役割"],
    summaryDifference: "ロールズは公正な制度設計を、マルクスは生産関係そのものの変革を重視する。",
    commonGround: "どちらも市場任せの格差拡大を問題視し、平等の政治的課題を明確化した。",
    sections: [
      { title: "格差の捉え方", leftView: "基本制度を公正化すれば格差は条件付きで許容可能。", rightView: "格差は資本主義構造から再生産されるため制度内調整では不十分。", takeaway: "制度修正か構造転換か。" },
      { title: "自由", leftView: "基本的自由の優先と機会平等を両立する。", rightView: "形式的自由ではなく搾取なき実質的自由を求める。", takeaway: "自由の形式条件と物質条件の差。" },
    ],
    nextThinkerSlugs: ["arendt", "mill", "rousseau"],
    nextComparisonSlugs: ["arendt-marx", "locke-rousseau", "kant-bentham"],
    nextThemeSlugs: ["justice", "state-legitimacy", "society-power"],
  },
  {
    slug: "hobbes-rousseau",
    leftThinkerSlug: "hobbes",
    rightThinkerSlug: "rousseau",
    titleJa: "秩序の契約 vs 自由の契約",
    subtitle: "国家は恐れからか、市民意志からか。",
    themeSlugs: ["freedom", "justice", "state-legitimacy"],
    whyThisComparisonMatters: "現代政治の権力観と民主観を比較できる。",
    whatToWatch: ["自然状態の人間像", "主権の位置", "自由の定義"],
    summaryDifference: "ホッブズは安全優先、ルソーは参加による自由優先。",
    commonGround: "契約によって政治秩序を説明する点は共通。",
    sections: [
      { title: "自然状態", leftView: "闘争と恐怖。", rightView: "本来は善だが社会が腐敗。", takeaway: "人間観が制度設計を左右。" },
      { title: "主権", leftView: "強い集中主権。", rightView: "一般意志による自己統治。", takeaway: "統治正当化の筋道が異なる。" },
    ],
    nextThinkerSlugs: ["locke", "rawls"],
    nextComparisonSlugs: ["hobbes-locke", "locke-rousseau"],
    nextThemeSlugs: ["state-legitimacy", "freedom"],
  },

  {
    slug: "husserl-heidegger",
    leftThinkerSlug: "husserl",
    rightThinkerSlug: "heidegger",
    titleJa: "フッサール vs ハイデガー",
    subtitle: "意識の記述から始めるか、存在理解から始めるか。",
    themeSlugs: ["human-nature", "truth", "knowledge"],
    whyThisComparisonMatters: "現象学から実存思想への分岐点を短く把握できる。",
    whatToWatch: ["哲学の出発点", "主体理解", "世界との関係"],
    summaryDifference: "フッサールは意識の志向性分析を、ハイデガーは世界内存在としての人間理解を重視。",
    commonGround: "どちらも素朴な主客二元論を超え、経験の現れ方を丁寧に問う。",
    sections: [
      { title: "出発点", leftView: "意識に与えられる現象を厳密に記述する。", rightView: "存在忘却を問い直し、人間のあり方から問う。", takeaway: "認識論的基礎づけと存在論的転回の差。" },
      { title: "人間像", leftView: "意味を構成する志向的主体。", rightView: "世界に投げ込まれた世界内存在。", takeaway: "主体中心と関係中心の違い。" },
    ],
    nextThinkerSlugs: ["sartre", "beauvoir"],
    nextComparisonSlugs: ["heidegger-sartre", "sartre-beauvoir"],
    nextThemeSlugs: ["human-nature", "freedom"],
  },
  {
    slug: "sartre-beauvoir",
    leftThinkerSlug: "sartre",
    rightThinkerSlug: "beauvoir",
    titleJa: "サルトル vs ボーヴォワール",
    subtitle: "自由の普遍理論か、状況に埋め込まれた自由か。",
    themeSlugs: ["freedom", "human-nature", "justice"],
    whyThisComparisonMatters: "実存主義を抽象概念で終わらせず、ジェンダーや関係性の問題へ橋渡しできる。",
    whatToWatch: ["自由の条件", "他者との関係", "抑圧の分析"],
    summaryDifference: "サルトルは選択責任の普遍性を、ボーヴォワールは状況と非対称性を重ねて自由を捉える。",
    commonGround: "どちらも本質主義を退け、人間が自己形成する存在だと考える。",
    sections: [
      { title: "自由", leftView: "人間はつねに選び、責任を引き受ける。", rightView: "自由は状況的制約の中で拡張される課題。", takeaway: "形式的自由と具体的自由の重心差。" },
      { title: "他者", leftView: "他者はしばしば自由を脅かす視線となる。", rightView: "他者との相互承認が解放の条件になる。", takeaway: "対立モデルと協働モデルの差。" },
    ],
    nextThinkerSlugs: ["arendt", "foucault"],
    nextComparisonSlugs: ["foucault-arendt", "heidegger-sartre"],
    nextThemeSlugs: ["freedom", "society-power"],
  },
  {
    slug: "arendt-marx",
    leftThinkerSlug: "arendt",
    rightThinkerSlug: "marx",
    titleJa: "アーレント vs マルクス",
    subtitle: "政治的行為の自由か、労働と生産関係の解放か。",
    themeSlugs: ["state-legitimacy", "society-power", "freedom"],
    whyThisComparisonMatters: "20世紀政治思想で、社会問題を政治へどう翻訳するかの対立軸を掴める。",
    whatToWatch: ["政治の中心概念", "労働の位置づけ", "解放の意味"],
    summaryDifference: "アーレントは公共空間での行為を、マルクスは生産関係の変革を解放の核心に置く。",
    commonGround: "どちらも近代社会の支配構造を批判し、人間の解放可能性を探る。",
    sections: [
      { title: "政治とは何か", leftView: "複数性の中での行為と言論。", rightView: "階級関係をめぐる闘争の場。", takeaway: "公共性中心と生産関係中心の差。" },
      { title: "自由", leftView: "他者と共に始める能力としての自由。", rightView: "搾取関係を超える実質的自由。", takeaway: "政治的自由と社会経済的自由の重点差。" },
    ],
    nextThinkerSlugs: ["foucault", "rawls"],
    nextComparisonSlugs: ["foucault-arendt", "rawls-marx"],
    nextThemeSlugs: ["society-power", "state-legitimacy"],
  },
  {
    slug: "heidegger-sartre",
    leftThinkerSlug: "heidegger",
    rightThinkerSlug: "sartre",
    titleJa: "ハイデガー vs サルトル",
    subtitle: "存在理解の分析か、自由な主体の責任か。",
    themeSlugs: ["human-nature", "freedom", "death"],
    whyThisComparisonMatters: "現象学から実存主義への継承と断絶を、最短で確認できる。",
    whatToWatch: ["主体概念", "不安と死", "実践倫理への接続"],
    summaryDifference: "ハイデガーは存在了解の地平を、サルトルは選択する主体の責任を前景化する。",
    commonGround: "どちらも人間を固定本質でなく、可能性へ開かれた存在として捉える。",
    sections: [
      { title: "人間像", leftView: "被投されつつ可能性へ先駆する存在。", rightView: "本質を持たず自己を選び続ける存在。", takeaway: "存在論的分析と主体倫理の差。" },
      { title: "自由", leftView: "固有性へ向かうあり方として自由を問う。", rightView: "選択回避できない責任として自由を問う。", takeaway: "自由の語り方が異なる。" },
    ],
    nextThinkerSlugs: ["beauvoir", "nietzsche"],
    nextComparisonSlugs: ["sartre-beauvoir", "nietzsche-sartre"],
    nextThemeSlugs: ["human-nature", "freedom"],
  },
  {
    slug: "foucault-arendt",
    leftThinkerSlug: "foucault",
    rightThinkerSlug: "arendt",
    titleJa: "フーコー vs アーレント",
    subtitle: "権力の網の目か、公共空間の行為か。",
    themeSlugs: ["society-power", "state-legitimacy", "freedom"],
    whyThisComparisonMatters: "20世紀の権力理解を、統治技術批判と公共性論の両面から比較できる。",
    whatToWatch: ["権力の所在", "主体化の過程", "抵抗と政治参加"],
    summaryDifference: "フーコーは制度と実践の微視的権力を、アーレントは公共的行為と複数性を重視する。",
    commonGround: "どちらも全体主義的支配を警戒し、自由を制度外の実践として捉える。",
    sections: [
      { title: "権力", leftView: "権力は分散し、身体や規範に浸透する。", rightView: "権力は公共空間の破壊で専制化する。", takeaway: "微視的分析と公共性分析の差。" },
      { title: "自由", leftView: "局所的実践の中で抵抗を組み立てる。", rightView: "他者と共に行為する場で自由が現れる。", takeaway: "抵抗中心と行為中心の違い。" },
    ],
    nextThinkerSlugs: ["marx", "beauvoir"],
    nextComparisonSlugs: ["arendt-marx", "sartre-beauvoir"],
    nextThemeSlugs: ["society-power", "state-legitimacy"],
  },
  {
    slug: "confucius-laozi",
    leftThinkerSlug: "confucius",
    rightThinkerSlug: "laozi",
    titleJa: "孔子 vs 老子",
    subtitle: "礼による秩序形成か、無為による過剰統治の抑制か。",
    themeSlugs: ["happiness", "state-legitimacy", "human-nature"],
    whyThisComparisonMatters: "東洋思想の入口として、規範形成と非介入の二つの政治倫理を短く比較できる。",
    whatToWatch: ["修養の位置づけ", "統治の強度", "人間理解"],
    summaryDifference: "孔子は礼と学びで秩序を育て、老子は作為を減らして調和を守る。",
    commonGround: "どちらも暴力的統治や過剰な利害追求を警戒する。",
    sections: [
      { title: "善く生きる道", leftView: "礼と仁の実践を積むことで人格を整える。", rightView: "欲望と操作を減らし、自然なリズムに戻る。", takeaway: "自己鍛錬中心か、脱力中心か。" },
      { title: "国家観", leftView: "徳ある為政者と教育が秩序の核になる。", rightView: "介入を抑える統治がかえって安定を生む。", takeaway: "政治の役割を厚く見るか薄く見るか。" },
    ],
    nextThinkerSlugs: ["mencius", "zhuangzi", "aristotle"],
    nextComparisonSlugs: ["confucius-mencius", "laozi-zhuangzi", "confucius-aristotle"],
    nextThemeSlugs: ["happiness", "state-legitimacy", "human-nature"],
  },
  {
    slug: "confucius-mencius",
    leftThinkerSlug: "confucius",
    rightThinkerSlug: "mencius",
    titleJa: "孔子 vs 孟子",
    subtitle: "礼の実践倫理をどう継承し、人間観をどう深めるか。",
    themeSlugs: ["happiness", "state-legitimacy", "human-nature"],
    whyThisComparisonMatters: "儒家内部の連続と差分を押さえると、東洋思想を単一の教訓集として誤解しにくくなる。",
    whatToWatch: ["人間の善性", "政治の役割", "修養の方法"],
    summaryDifference: "孔子は礼と関係秩序の実践を基礎づけ、孟子は性善説から仁政を理論化する。",
    commonGround: "どちらも人格形成と政治秩序を切り離さずに考える。",
    sections: [
      { title: "人間理解", leftView: "学びと慣習で徳を育てる。", rightView: "善の芽が人間に備わると捉える。", takeaway: "修養中心か、善性前提か。" },
      { title: "国家の正当化", leftView: "徳による統治が秩序の条件。", rightView: "民生を守る仁政が統治の正当性を支える。", takeaway: "徳治の継承と政治理論化。" },
    ],
    nextThinkerSlugs: ["xunzi", "mozi", "aristotle"],
    nextComparisonSlugs: ["mencius-xunzi", "mozi-mencius", "confucius-aristotle"],
    nextThemeSlugs: ["state-legitimacy", "human-nature"],
  },
  {
    slug: "laozi-zhuangzi",
    leftThinkerSlug: "laozi",
    rightThinkerSlug: "zhuangzi",
    titleJa: "老子 vs 荘子",
    subtitle: "道への回帰か、視点の遊びによる自由化か。",
    themeSlugs: ["happiness", "freedom", "human-nature"],
    whyThisComparisonMatters: "道家の共通地盤を確認しつつ、老子と荘子の実践スタイルの違いを初学者向けに見分けられる。",
    whatToWatch: ["無為の意味", "自由の捉え方", "言葉への態度"],
    summaryDifference: "老子は統治と生の過剰介入を抑え、荘子は視点相対化で執着をほどく。",
    commonGround: "どちらも固定規範と過度な自己主張を和らげる方向を示す。",
    sections: [
      { title: "実践の軸", leftView: "無為を通じて介入を減らす。", rightView: "寓話と転換で立場への固着を崩す。", takeaway: "抑制の哲学か、遊動の哲学か。" },
      { title: "人間像", leftView: "自然に沿うことで均衡を保つ。", rightView: "視点を行き来しながら自由を広げる。", takeaway: "調和中心と可塑性中心の違い。" },
    ],
    nextThinkerSlugs: ["confucius", "wittgenstein"],
    nextComparisonSlugs: ["confucius-zhuangzi"],
    nextThemeSlugs: ["freedom", "human-nature"],
  },
  {
    slug: "confucius-zhuangzi",
    leftThinkerSlug: "confucius",
    rightThinkerSlug: "zhuangzi",
    titleJa: "孔子 vs 荘子",
    subtitle: "関係秩序の鍛錬か、規範の相対化による解放か。",
    themeSlugs: ["happiness", "human-nature", "freedom"],
    whyThisComparisonMatters: "東洋思想内部で、規範形成と規範批判の緊張を一度に確認できる。",
    whatToWatch: ["礼の位置", "自由の意味", "社会との距離"],
    summaryDifference: "孔子は役割倫理を通じ秩序を育て、荘子は固定役割をゆるめ自由を確保する。",
    commonGround: "どちらも人間の生を単なる利害計算へ還元しない。",
    sections: [
      { title: "社会との関わり", leftView: "役割を引き受けて関係を整える。", rightView: "役割への執着を外し柔軟に生きる。", takeaway: "参与の倫理か、距離化の倫理か。" },
      { title: "人間観", leftView: "学びで徳を蓄積できる。", rightView: "立場の変化に応じて自己をほどける。", takeaway: "形成可能性の異なる描き方。" },
    ],
    nextThinkerSlugs: ["mencius", "aristotle"],
    nextComparisonSlugs: ["confucius-mencius", "confucius-aristotle"],
    nextThemeSlugs: ["human-nature", "happiness"],
  },
  {
    slug: "confucius-aristotle",
    leftThinkerSlug: "confucius",
    rightThinkerSlug: "aristotle",
    titleJa: "孔子 vs アリストテレス",
    subtitle: "徳は関係の中で磨くか、習慣と理性で形成するか。",
    themeSlugs: ["happiness", "human-nature", "state-legitimacy"],
    whyThisComparisonMatters: "東洋思想と既存ネットワークを無理なく接続し、徳倫理の複数モデルを比較できる橋になる。",
    whatToWatch: ["徳形成の方法", "共同体理解", "政治と倫理の連続性"],
    summaryDifference: "孔子は礼と関係的責務を、アリストテレスは習慣と中庸を徳形成の軸に置く。",
    commonGround: "どちらも善い生を共同体的実践と結びつける。",
    sections: [
      { title: "徳の育ち方", leftView: "礼と模範の反復で徳を磨く。", rightView: "習慣化と理性的判断で中庸を身につける。", takeaway: "関係規範中心か、徳目分析中心か。" },
      { title: "政治への接続", leftView: "徳ある統治者と教育を重視。", rightView: "ポリスの制度と市民実践を重視。", takeaway: "統治倫理の焦点の違い。" },
    ],
    nextThinkerSlugs: ["plato", "mencius", "epictetus"],
    nextComparisonSlugs: ["plato-aristotle", "aristotle-stoicism", "confucius-mencius"],
    nextThemeSlugs: ["happiness", "human-nature"],
  },
  {
    slug: "mencius-xunzi",
    leftThinkerSlug: "mencius",
    rightThinkerSlug: "xunzi",
    titleJa: "孟子 vs 荀子",
    subtitle: "性善か性悪か。秩序形成の前提となる人間観を比べる。",
    themeSlugs: ["human-nature", "state-legitimacy", "happiness"],
    whyThisComparisonMatters: "東洋思想第二層の中核対比として、人間観の差が倫理と統治設計をどう分けるかを掴める。",
    whatToWatch: ["人間本性", "教育の役割", "統治の強度"],
    summaryDifference: "孟子は善性の伸長を、荀子は欲望統御の訓練を重視する。",
    commonGround: "どちらも放任ではなく、教育と政治の働きを重視する。",
    sections: [
      { title: "人間観", leftView: "人には善の芽が備わる。", rightView: "人は欲望に流れやすく矯正が要る。", takeaway: "善性前提と統御前提の差。" },
      { title: "統治", leftView: "仁政で民を養い徳を伸ばす。", rightView: "礼法による訓練で秩序を維持する。", takeaway: "育成中心と規律中心の違い。" },
    ],
    nextThinkerSlugs: ["hanfeizi", "hobbes", "confucius"],
    nextComparisonSlugs: ["xunzi-hanfeizi", "hanfeizi-hobbes", "confucius-mencius"],
    nextThemeSlugs: ["human-nature", "state-legitimacy"],
  },
  {
    slug: "confucius-mozi",
    leftThinkerSlug: "confucius",
    rightThinkerSlug: "mozi",
    titleJa: "孔子 vs 墨子",
    subtitle: "礼にもとづく関係倫理か、兼愛にもとづく普遍的配慮か。",
    themeSlugs: ["happiness", "state-legitimacy", "justice"],
    whyThisComparisonMatters: "儒家と墨家の分岐を押さえると、徳・礼・利益の緊張を初心者でも整理しやすい。",
    whatToWatch: ["愛の範囲", "儀礼の評価", "政策基準"],
    summaryDifference: "孔子は関係秩序と礼を重視し、墨子は兼愛と実利で政策を測る。",
    commonGround: "どちらも乱世を前提に、社会秩序の再建を目指す。",
    sections: [
      { title: "倫理", leftView: "役割に応じた仁と礼を育てる。", rightView: "身分を超えた兼愛を求める。", takeaway: "差等的配慮と普遍的配慮の差。" },
      { title: "統治", leftView: "徳と教育で共同体を整える。", rightView: "有効性と利害調整で制度を評価する。", takeaway: "徳治中心と実利中心の違い。" },
    ],
    nextThinkerSlugs: ["mencius", "xunzi", "bentham"],
    nextComparisonSlugs: ["mozi-mencius", "mencius-xunzi", "kant-bentham"],
    nextThemeSlugs: ["happiness", "state-legitimacy", "justice"],
  },
  {
    slug: "xunzi-hanfeizi",
    leftThinkerSlug: "xunzi",
    rightThinkerSlug: "hanfeizi",
    titleJa: "荀子 vs 韓非子",
    subtitle: "礼法による教化か、法術勢による統治設計か。",
    themeSlugs: ["state-legitimacy", "human-nature", "society-power"],
    whyThisComparisonMatters: "儒家的現実主義から法家への転回を比較すると、徳と法の配分問題が明確になる。",
    whatToWatch: ["徳の役割", "法の位置", "君主観"],
    summaryDifference: "荀子は礼による教化を残し、韓非子は制度と法の運用を前面化する。",
    commonGround: "どちらも人間の欲望と秩序維持を現実的に扱う。",
    sections: [
      { title: "秩序形成", leftView: "礼で欲望を整え社会を教化する。", rightView: "法と罰で行動を統制する。", takeaway: "教化重視か統制重視か。" },
      { title: "統治者", leftView: "規範を体現し制度を運用する。", rightView: "術で官僚を管理し権勢を維持する。", takeaway: "規範的統治と技術的統治の差。" },
    ],
    nextThinkerSlugs: ["hobbes", "confucius", "mencius"],
    nextComparisonSlugs: ["hanfeizi-hobbes", "confucius-mencius", "hobbes-locke"],
    nextThemeSlugs: ["state-legitimacy", "society-power"],
  },
  {
    slug: "mozi-mencius",
    leftThinkerSlug: "mozi",
    rightThinkerSlug: "mencius",
    titleJa: "墨子 vs 孟子",
    subtitle: "普遍的利益の最大化か、徳性の育成と仁政か。",
    themeSlugs: ["happiness", "state-legitimacy", "human-nature"],
    whyThisComparisonMatters: "結果重視と徳性重視の差を東洋思想内部で比較でき、倫理・政治の読み筋が広がる。",
    whatToWatch: ["政策評価", "人間観", "平等観"],
    summaryDifference: "墨子は実利と兼愛を基準にし、孟子は善性と仁政を基準にする。",
    commonGround: "どちらも為政者の恣意や暴政を批判する。",
    sections: [
      { title: "善の基準", leftView: "多くを利するかで判断する。", rightView: "善性を育てるかで判断する。", takeaway: "帰結基準と徳性基準の差。" },
      { title: "国家", leftView: "尚賢と節約で統治効率を上げる。", rightView: "民心を得る仁政で正当性を確保する。", takeaway: "効率中心と民心中心の違い。" },
    ],
    nextThinkerSlugs: ["xunzi", "confucius", "bentham"],
    nextComparisonSlugs: ["mencius-xunzi", "confucius-mozi", "bentham-mill"],
    nextThemeSlugs: ["happiness", "state-legitimacy"],
  },
  {
    slug: "hanfeizi-hobbes",
    leftThinkerSlug: "hanfeizi",
    rightThinkerSlug: "hobbes",
    titleJa: "韓非子 vs ホッブズ",
    subtitle: "法と権勢の統治か、契約主権による秩序か。",
    themeSlugs: ["state-legitimacy", "human-nature", "society-power"],
    whyThisComparisonMatters: "東洋思想第二弾から既存の政治思想ネットワークへ接続する、慎重な橋渡し比較として機能する。",
    whatToWatch: ["人間観", "主権正当化", "法の役割"],
    summaryDifference: "韓非子は制度運用と権勢を、ホッブズは契約による主権正当化を重視する。",
    commonGround: "どちらも無秩序への不安を出発点に強い統治を擁護する。",
    sections: [
      { title: "秩序の根拠", leftView: "法・術・勢の設計と運用。", rightView: "自然状態回避のための契約。", takeaway: "実務統治モデルと契約理論モデルの差。" },
      { title: "国家像", leftView: "君主主導で官僚を制御する。", rightView: "主権者に権限を集中し内戦を防ぐ。", takeaway: "統治技術中心と契約正当化中心の違い。" },
    ],
    nextThinkerSlugs: ["locke", "rousseau", "xunzi"],
    nextComparisonSlugs: ["hobbes-locke", "hobbes-rousseau", "xunzi-hanfeizi"],
    nextThemeSlugs: ["state-legitimacy", "society-power"],
  },
  {
    slug: "kant-nietzsche",
    leftThinkerSlug: "kant",
    rightThinkerSlug: "nietzsche",
    titleJa: "普遍道徳 vs 価値の再評価",
    subtitle: "道徳は理性で立つか、生成し直すか。",
    themeSlugs: ["freedom", "happiness"],
    whyThisComparisonMatters: "近代以降の倫理観の分裂を捉える。",
    whatToWatch: ["道徳の根拠", "主体像", "責任の意味"],
    summaryDifference: "カントは普遍的義務、ニーチェは価値創造を重視。",
    commonGround: "どちらも受動的慣習道徳を批判。",
    sections: [
      { title: "道徳根拠", leftView: "理性の普遍法則。", rightView: "力と生の解釈。", takeaway: "倫理の普遍性を巡る対立。" },
      { title: "自由", leftView: "自律としての自由。", rightView: "自己超克としての自由。", takeaway: "自由の厚みが異なる。" },
    ],
    nextThinkerSlugs: ["sartre", "heidegger"],
    nextComparisonSlugs: ["nietzsche-sartre", "heidegger-sartre"],
    nextThemeSlugs: ["freedom", "human-nature"],
  },
  {
    slug: "nietzsche-sartre",
    leftThinkerSlug: "nietzsche",
    rightThinkerSlug: "sartre",
    titleJa: "価値創造 vs 実存責任",
    subtitle: "神なき時代にどう生きるか。",
    themeSlugs: ["freedom", "death"],
    whyThisComparisonMatters: "実存主義への流れを比較で掴める。",
    whatToWatch: ["自己形成", "他者", "責任"],
    summaryDifference: "ニーチェは価値再評価、サルトルは選択責任を強調。",
    commonGround: "既存本質への依存を退ける。",
    sections: [
      { title: "主体", leftView: "力への意志で再評価。", rightView: "投企として自己形成。", takeaway: "自己像の実践方法が異なる。" },
      { title: "倫理", leftView: "貴族的価値の創造。", rightView: "普遍化なき責任倫理。", takeaway: "価値創出と責任の重み。" },
    ],
    nextThinkerSlugs: ["heidegger", "beauvoir"],
    nextComparisonSlugs: ["heidegger-sartre", "sartre-beauvoir"],
    nextThemeSlugs: ["freedom", "human-nature"],
  },
];
