import { Comparison } from "@/types/content";

export const comparisons: Comparison[] = [
  {
    slug: "plato-aristotle",
    leftThinkerSlug: "plato",
    rightThinkerSlug: "aristotle",
    titleJa: "イデア論 vs 実体論",
    subtitle: "理想から世界を見るか、個物から見るか。",
    themeSlugs: ["knowledge", "justice"],
    whyThisComparisonMatters: "西洋哲学の基礎的な分岐を最短でつかめる。",
    whatToWatch: ["本質の場所", "認識の起点", "政治秩序の設計"],
    summaryDifference: "プラトンは超越的普遍を、アリストテレスは内在的本質を重視。",
    commonGround: "両者とも理性的探究によってより良い生を目指した。",
    sections: [
      { title: "本質はどこにあるか", leftView: "イデア界に真の実在がある。", rightView: "個物の中に実体としてある。", takeaway: "超越と内在の対比。" },
      { title: "知の獲得", leftView: "想起と弁証法。", rightView: "観察と分類。", takeaway: "方法論の差が学問観を分ける。" },
    ],
    nextThinkerSlugs: ["kant", "confucius"],
    nextComparisonSlugs: ["descartes-hume"],
    nextThemeSlugs: ["knowledge"],
  },
  {
    slug: "descartes-hume",
    leftThinkerSlug: "descartes",
    rightThinkerSlug: "hume",
    titleJa: "合理主義 vs 経験主義",
    subtitle: "確実性は理性か経験か。",
    themeSlugs: ["knowledge", "language"],
    whyThisComparisonMatters: "カントへ向かう近代認識論の核心を短く理解できる。",
    whatToWatch: ["知識の源泉", "因果の正当化", "自我の確実性"],
    summaryDifference: "デカルトは理性の明証性、ヒュームは経験の習慣性を重視。",
    commonGround: "両者とも確実な知の条件を厳密に問うた。",
    sections: [
      { title: "知識の基礎", leftView: "コギトと生得観念。", rightView: "印象と観念の連合。", takeaway: "確実性の定義が異なる。" },
      { title: "因果", leftView: "理性で必然を捉える。", rightView: "必然は経験的習慣。", takeaway: "科学観と懐疑の温度差。" },
    ],
    nextThinkerSlugs: ["kant", "wittgenstein"],
    nextComparisonSlugs: ["hume-kant"],
    nextThemeSlugs: ["knowledge"],
  },
  {
    slug: "hume-kant",
    leftThinkerSlug: "hume",
    rightThinkerSlug: "kant",
    titleJa: "懐疑から批判へ",
    subtitle: "経験の限界をどう超えるか。",
    themeSlugs: ["knowledge", "freedom"],
    whyThisComparisonMatters: "近代哲学の転回点をつかむ。",
    whatToWatch: ["先験的条件", "因果の地位", "道徳の根拠"],
    summaryDifference: "ヒュームは正当化の縮減、カントは条件の再構成。",
    commonGround: "双方とも独断を避け、認識の限界を重視した。",
    sections: [
      { title: "経験の位置づけ", leftView: "経験は習慣の束。", rightView: "経験は先験的形式で成立。", takeaway: "限界論から構成論へ。" },
      { title: "道徳", leftView: "感情を中心に説明。", rightView: "理性の自律で基礎づけ。", takeaway: "倫理の重心が移る。" },
    ],
    nextThinkerSlugs: ["nietzsche"],
    nextComparisonSlugs: ["kant-nietzsche"],
    nextThemeSlugs: ["freedom"],
  },
  {
    slug: "hobbes-rousseau",
    leftThinkerSlug: "hobbes",
    rightThinkerSlug: "rousseau",
    titleJa: "秩序の契約 vs 自由の契約",
    subtitle: "国家は恐れからか、市民意志からか。",
    themeSlugs: ["freedom", "justice"],
    whyThisComparisonMatters: "現代政治の権力観と民主観を比較できる。",
    whatToWatch: ["自然状態の人間像", "主権の位置", "自由の定義"],
    summaryDifference: "ホッブズは安全優先、ルソーは参加による自由優先。",
    commonGround: "契約によって政治秩序を説明する点は共通。",
    sections: [
      { title: "自然状態", leftView: "闘争と恐怖。", rightView: "本来は善だが社会が腐敗。", takeaway: "人間観が制度設計を左右。" },
      { title: "主権", leftView: "強い集中主権。", rightView: "一般意志による自己統治。", takeaway: "統治正当化の筋道が異なる。" },
    ],
    nextThinkerSlugs: ["kant", "sartre"],
    nextComparisonSlugs: ["kant-nietzsche"],
    nextThemeSlugs: ["justice"],
  },
  {
    slug: "confucius-laozi",
    leftThinkerSlug: "confucius",
    rightThinkerSlug: "laozi",
    titleJa: "礼の秩序 vs 無為自然",
    subtitle: "社会を整えるのは規範か、脱規範か。",
    themeSlugs: ["happiness", "justice"],
    whyThisComparisonMatters: "東アジア思想の二大軸を比較できる。",
    whatToWatch: ["徳の形成", "統治の理想", "言語と実践"],
    summaryDifference: "孔子は修養と礼、老子は柔弱と無為を重視。",
    commonGround: "ともに過剰な暴力政治を批判する。",
    sections: [
      { title: "人間形成", leftView: "学びと礼で徳を鍛える。", rightView: "作為を減らし自然に戻る。", takeaway: "規範強化と規範緩和。" },
      { title: "統治", leftView: "徳治で秩序化。", rightView: "非干渉で均衡化。", takeaway: "権力行使の度合いが対照的。" },
    ],
    nextThinkerSlugs: ["plato", "wittgenstein"],
    nextComparisonSlugs: ["plato-aristotle"],
    nextThemeSlugs: ["happiness"],
  },
  {
    slug: "kant-nietzsche",
    leftThinkerSlug: "kant",
    rightThinkerSlug: "nietzsche",
    titleJa: "普遍道徳 vs 価値の再評価",
    subtitle: "道徳は理性で立つか、生成し直すか。",
    themeSlugs: ["freedom", "happiness"],
    whyThisComparisonMatters: "近代以降の倫理観の分裂を捉える。",
    whatToWatch: ["道徳の根拠", "主体像", "責任の意味"],
    summaryDifference: "カントは普遍的義務、ニーチェは価値創造を重視。",
    commonGround: "どちらも受動的慣習道徳を批判。",
    sections: [
      { title: "道徳根拠", leftView: "理性の普遍法則。", rightView: "力と生の解釈。", takeaway: "倫理の普遍性を巡る対立。" },
      { title: "自由", leftView: "自律としての自由。", rightView: "自己超克としての自由。", takeaway: "自由の厚みが異なる。" },
    ],
    nextThinkerSlugs: ["sartre"],
    nextComparisonSlugs: ["nietzsche-sartre"],
    nextThemeSlugs: ["freedom"],
  },
  {
    slug: "nietzsche-sartre",
    leftThinkerSlug: "nietzsche",
    rightThinkerSlug: "sartre",
    titleJa: "価値創造 vs 実存責任",
    subtitle: "神なき時代にどう生きるか。",
    themeSlugs: ["freedom", "death"],
    whyThisComparisonMatters: "実存主義への流れを比較で掴める。",
    whatToWatch: ["自己形成", "他者", "責任"],
    summaryDifference: "ニーチェは価値再評価、サルトルは選択責任を強調。",
    commonGround: "既存本質への依存を退ける。",
    sections: [
      { title: "主体", leftView: "力への意志で再評価。", rightView: "投企として自己形成。", takeaway: "自己像の実践方法が異なる。" },
      { title: "倫理", leftView: "貴族的価値の創造。", rightView: "普遍化なき責任倫理。", takeaway: "価値創出と責任の重み。" },
    ],
    nextThinkerSlugs: ["wittgenstein"],
    nextComparisonSlugs: ["descartes-hume"],
    nextThemeSlugs: ["death"],
  },
];
