import { Theme } from "@/types/content";

export const themes: Theme[] = [
  {
    slug: "knowledge",
    titleJa: "知識",
    titleEn: "Knowledge",
    shortDescription: "私たちは何を、どうやって知れるのか。",
    relatedThinkerSlugs: ["plato", "aristotle", "descartes", "locke", "leibniz", "berkeley", "hume", "kant", "wittgenstein"],
    relatedComparisonSlugs: ["plato-aristotle", "descartes-locke", "leibniz-locke", "locke-hume", "berkeley-locke", "descartes-hume", "hume-kant"],
    starterGuidance: "まずデカルト vs ロックで入口を掴み、ロック vs ヒューム、ヒューム vs カントへ進む。",
  },
  {
    slug: "truth",
    titleJa: "真理",
    titleEn: "Truth",
    shortDescription: "真理はどのように保証され、どこまで到達できるのか。",
    relatedThinkerSlugs: ["plato", "aristotle", "descartes", "spinoza", "locke", "leibniz", "berkeley", "hume", "kant", "wittgenstein"],
    relatedComparisonSlugs: ["plato-aristotle", "descartes-locke", "spinoza-descartes", "leibniz-locke", "berkeley-locke", "locke-hume", "descartes-hume", "hume-kant", "plato-epicurus"],
    starterGuidance: "デカルト vs ロックで真理の基準を比べ、スピノザ vs デカルトで合理論内部の違いを確認する。",
  },
  {
    slug: "human-nature",
    titleJa: "人間とは何か",
    titleEn: "Human Nature",
    shortDescription: "人間は欲望・理性・共同体の中でどう生きる存在か。",
    relatedThinkerSlugs: ["plato", "aristotle", "epicurus", "zeno", "epictetus", "marcus-aurelius", "confucius", "mencius", "xunzi", "mozi", "hanfeizi", "laozi", "zhuangzi", "nietzsche", "sartre", "husserl", "heidegger", "beauvoir", "foucault"],
    relatedComparisonSlugs: ["stoicism-epicureanism", "aristotle-stoicism", "plato-epicurus", "epictetus-epicurus", "marcus-epictetus", "confucius-laozi", "confucius-zhuangzi", "laozi-zhuangzi", "mencius-xunzi", "xunzi-hanfeizi", "mozi-mencius", "nietzsche-sartre", "husserl-heidegger", "heidegger-sartre", "sartre-beauvoir"],
    starterGuidance: "まず孟子 vs 荀子で人間観の分岐を掴み、次に荀子 vs 韓非子で秩序設計の差へ進む。",
  },
  {
    slug: "state-legitimacy",
    titleJa: "国家の正当性",
    titleEn: "State Legitimacy",
    shortDescription: "国家は何を根拠に権力を行使できるのか。",
    relatedThinkerSlugs: ["hobbes", "locke", "rousseau", "bentham", "mill", "rawls", "marx", "arendt", "foucault", "confucius", "mencius", "xunzi", "mozi", "hanfeizi", "laozi"],
    relatedComparisonSlugs: ["hobbes-locke", "locke-rousseau", "hobbes-rousseau", "kant-bentham", "rawls-marx", "bentham-mill", "arendt-marx", "foucault-arendt", "confucius-laozi", "confucius-mencius", "mencius-xunzi", "xunzi-hanfeizi", "hanfeizi-hobbes", "confucius-mozi"],
    starterGuidance: "まず荀子 vs 韓非子で秩序形成の設計差を見て、次に韓非子 vs ホッブズで既存政治思想ネットワークへ接続する。",
  },
  {
    slug: "freedom",
    titleJa: "自由",
    titleEn: "Freedom",
    shortDescription: "自由は選択か、制度か、自己創造か。",
    relatedThinkerSlugs: ["spinoza", "hume", "kant", "hobbes", "locke", "rousseau", "mill", "rawls", "marx", "epicurus", "zeno", "epictetus", "marcus-aurelius", "laozi", "zhuangzi", "nietzsche", "sartre", "heidegger", "beauvoir", "arendt"],
    relatedComparisonSlugs: ["stoicism-epicureanism", "epictetus-epicurus", "marcus-epictetus", "aristotle-stoicism", "laozi-zhuangzi", "confucius-zhuangzi", "spinoza-descartes", "hobbes-locke", "locke-rousseau", "hobbes-rousseau", "bentham-mill", "rawls-marx", "hume-kant", "kant-nietzsche", "nietzsche-sartre", "heidegger-sartre", "sartre-beauvoir", "foucault-arendt"],
    starterGuidance: "まずニーチェ vs サルトルで実存的自由を掴み、ハイデガー vs サルトルとサルトル vs ボーヴォワールで20世紀の展開へ進む。",
  },
  {
    slug: "happiness",
    titleJa: "幸福",
    titleEn: "Happiness",
    shortDescription: "善く生きるとは快か徳か、それとも調和か。",
    relatedThinkerSlugs: ["plato", "aristotle", "epicurus", "zeno", "epictetus", "marcus-aurelius", "confucius", "mencius", "xunzi", "mozi", "laozi", "zhuangzi", "kant", "bentham", "mill", "nietzsche"],
    relatedComparisonSlugs: ["stoicism-epicureanism", "aristotle-stoicism", "plato-epicurus", "epictetus-epicurus", "marcus-epictetus", "kant-bentham", "bentham-mill", "kant-nietzsche", "confucius-laozi", "confucius-mencius", "mencius-xunzi", "mozi-mencius", "confucius-mozi", "laozi-zhuangzi", "confucius-aristotle"],
    starterGuidance: "まず孔子 vs 墨子で徳と利益の軸差を見て、次に墨子 vs 孟子で善の基準の違いを比較する。",
  },
  {
    slug: "justice",
    titleJa: "正義",
    titleEn: "Justice",
    shortDescription: "秩序と平等、共同体と個人の両立を考える。",
    relatedThinkerSlugs: ["plato", "locke", "kant", "rousseau", "hobbes", "bentham", "rawls", "marx", "beauvoir", "arendt", "confucius", "mencius"],
    relatedComparisonSlugs: ["plato-aristotle", "hobbes-locke", "locke-rousseau", "kant-bentham", "rawls-marx", "arendt-marx", "sartre-beauvoir", "hobbes-rousseau", "confucius-mencius"],
    starterGuidance: "ロールズ vs マルクスで平等問題の現代的対立を掴んだ後、ロック vs ルソーで政治参加の論点へ戻る。",
  },
  {
    slug: "society-power",
    titleJa: "社会と権力はどう成り立つか",
    titleEn: "Society and Power",
    shortDescription: "制度・労働・公共空間の中で権力はどう働くか。",
    relatedThinkerSlugs: ["marx", "arendt", "foucault", "beauvoir", "hobbes", "rawls", "hanfeizi", "xunzi"],
    relatedComparisonSlugs: ["rawls-marx", "arendt-marx", "foucault-arendt", "sartre-beauvoir", "hobbes-rousseau", "xunzi-hanfeizi", "hanfeizi-hobbes"],
    starterGuidance: "まず荀子 vs 韓非子で統治技術の差を押さえ、次に韓非子 vs ホッブズで主権正当化の比較へ進む。",
  },
  {
    slug: "death",
    titleJa: "死",
    titleEn: "Death",
    shortDescription: "有限性は自由と意味をどう変えるか。",
    relatedThinkerSlugs: ["plato", "sartre", "nietzsche", "epicurus"],
    relatedComparisonSlugs: ["nietzsche-sartre", "epictetus-epicurus"],
    starterGuidance: "ニーチェ vs サルトルで有限性と責任の差を見たあと、エピクテトス vs エピクロスで不安対処を比較する。",
  },
  {
    slug: "language",
    titleJa: "言語",
    titleEn: "Language",
    shortDescription: "言語は世界を写すのか、作るのか。",
    relatedThinkerSlugs: ["descartes", "wittgenstein", "laozi"],
    relatedComparisonSlugs: ["descartes-hume"],
    starterGuidance: "ウィトゲンシュタインに進む前にデカルト vs ヒュームを押さえる。",
  },
];
