import { Thinker } from "@/types/content";

export const thinkers: Thinker[] = [
  {
    slug: "plato",
    nameJa: "プラトン",
    nameEn: "Plato",
    eraLabel: "古代ギリシア",
    yearsLabel: "c. 427–347 BCE",
    oneLiner: "変わらない真理の世界を想定し、現実を読み解いた。",
    quote: "哲学とは死の練習である。",
    coreQuestion: "変化する世界の背後に普遍はあるか。",
    basicAnswer: "感覚世界の背後にイデアという真の実在がある。",
    opposedTo: "アリストテレスの実体論",
    epistemology: "想起説と弁証法で普遍知へ到達する。",
    viewOfHuman: "魂は理性的秩序へ向かう存在。",
    ethicalPoliticalImplication: "徳と統治は知に基づくべきだ。",
    laterInfluence: "新プラトン主義、キリスト教神学、観念論に影響。",
    keyConcepts: ["イデア", "魂", "哲人王"],
    keyWorks: ["国家", "饗宴", "パイドン"],
    relatedThemeSlugs: ["knowledge", "justice"],
    relatedThinkerSlugs: ["aristotle", "kant"],
    relatedComparisonSlugs: ["plato-aristotle"],
  },
  {
    slug: "aristotle",
    nameJa: "アリストテレス",
    nameEn: "Aristotle",
    eraLabel: "古代ギリシア",
    yearsLabel: "384–322 BCE",
    oneLiner: "観察と分類から世界の秩序を記述した。",
    quote: "人間はポリス的動物である。",
    coreQuestion: "ものごとの本質はどこに宿るか。",
    basicAnswer: "本質は個物の内にある実体として理解できる。",
    opposedTo: "プラトンのイデア論",
    epistemology: "経験から普遍を抽出する。",
    viewOfHuman: "理性と実践を通じ徳を形成する存在。",
    ethicalPoliticalImplication: "中庸と共同体倫理が重要。",
    laterInfluence: "中世スコラ学から近代科学の方法論まで接続。",
    keyConcepts: ["実体", "四原因", "中庸"],
    keyWorks: ["形而上学", "ニコマコス倫理学", "政治学"],
    relatedThemeSlugs: ["knowledge", "happiness"],
    relatedThinkerSlugs: ["plato", "aquinas"],
    relatedComparisonSlugs: ["plato-aristotle"],
  },
  { slug: "descartes", nameJa: "デカルト", nameEn: "René Descartes", eraLabel: "近代", yearsLabel: "1596–1650", oneLiner: "方法的懐疑で確実性を探した。", quote: "我思う、ゆえに我あり。", coreQuestion: "疑い得ない知の出発点は何か。", basicAnswer: "思考する自我の確実性が基礎になる。", opposedTo: "ヒュームの経験論的懐疑", epistemology: "生得観念と演繹理性を重視。", viewOfHuman: "心身二元論で理性的主体を中心化。", ethicalPoliticalImplication: "普遍的理性への信頼を強化。", laterInfluence: "合理主義と近代主体概念の土台。", keyConcepts: ["方法的懐疑", "コギト", "心身二元論"], keyWorks: ["方法序説", "省察"], relatedThemeSlugs: ["knowledge", "language"], relatedThinkerSlugs: ["hume", "kant"], relatedComparisonSlugs: ["descartes-hume"] },
  { slug: "hume", nameJa: "ヒューム", nameEn: "David Hume", eraLabel: "近代", yearsLabel: "1711–1776", oneLiner: "経験の限界を徹底し、因果と自我を問い直した。", quote: "理性は情念の奴隷である。", coreQuestion: "私たちは何を正当化できるのか。", basicAnswer: "確実性ではなく習慣と蓋然性が認識を支える。", opposedTo: "デカルト的合理主義", epistemology: "印象と観念、懐疑的経験論。", viewOfHuman: "理性より情念と習慣に導かれる。", ethicalPoliticalImplication: "道徳感情と慣習の役割を重視。", laterInfluence: "カントの批判哲学を刺激。", keyConcepts: ["因果の習慣説", "束としての自我", "帰納問題"], keyWorks: ["人間本性論", "人間知性研究"], relatedThemeSlugs: ["knowledge", "freedom"], relatedThinkerSlugs: ["descartes", "kant"], relatedComparisonSlugs: ["descartes-hume", "hume-kant"] },
  { slug: "kant", nameJa: "カント", nameEn: "Immanuel Kant", eraLabel: "近代", yearsLabel: "1724–1804", oneLiner: "経験と理性の条件を批判的に統合した。", quote: "啓蒙とは、人間が未成年状態から抜け出すこと。", coreQuestion: "経験が成立する条件は何か。", basicAnswer: "主体の先験的形式が経験を可能にする。", opposedTo: "経験論と独断的合理論の双方", epistemology: "先験論的観念論。", viewOfHuman: "自律的に法を立てる理性的存在。", ethicalPoliticalImplication: "人格の尊厳と義務倫理。", laterInfluence: "ドイツ観念論、現代倫理学に巨大な影響。", keyConcepts: ["先験的", "定言命法", "物自体"], keyWorks: ["純粋理性批判", "実践理性批判"], relatedThemeSlugs: ["knowledge", "freedom", "justice"], relatedThinkerSlugs: ["hume", "nietzsche"], relatedComparisonSlugs: ["hume-kant", "kant-nietzsche"] },
  { slug: "rousseau", nameJa: "ルソー", nameEn: "Jean-Jacques Rousseau", eraLabel: "近代", yearsLabel: "1712–1778", oneLiner: "自由と共同体を一般意志で再定義した。", quote: "人間は自由なものとして生まれ、至るところで鎖につながれている。", coreQuestion: "自由は共同体でどう守られるか。", basicAnswer: "一般意志への参与で市民的自由を実現する。", opposedTo: "ホッブズ的統治観", epistemology: "文明批判と道徳感情。", viewOfHuman: "本性的善性を持つが社会で歪む。", ethicalPoliticalImplication: "民主主義理論へ影響。", laterInfluence: "革命思想、教育論、ロマン主義。", keyConcepts: ["一般意志", "社会契約", "市民教育"], keyWorks: ["社会契約論", "エミール"], relatedThemeSlugs: ["freedom", "justice"], relatedThinkerSlugs: ["hobbes", "mill"], relatedComparisonSlugs: ["hobbes-rousseau"] },
  { slug: "hobbes", nameJa: "ホッブズ", nameEn: "Thomas Hobbes", eraLabel: "近代", yearsLabel: "1588–1679", oneLiner: "秩序維持のため主権国家を理論化した。", quote: "万人の万人に対する闘争。", coreQuestion: "なぜ国家が必要か。", basicAnswer: "自然状態の不安を避けるため契約で主権を立てる。", opposedTo: "ルソーの一般意志中心の契約", epistemology: "機械論的自然観。", viewOfHuman: "自己保存を優先する存在。", ethicalPoliticalImplication: "強い主権と秩序を正当化。", laterInfluence: "近代国家論と政治的リアリズム。", keyConcepts: ["自然状態", "契約", "リヴァイアサン"], keyWorks: ["リヴァイアサン"], relatedThemeSlugs: ["freedom", "justice"], relatedThinkerSlugs: ["rousseau", "mill"], relatedComparisonSlugs: ["hobbes-rousseau"] },
  { slug: "nietzsche", nameJa: "ニーチェ", nameEn: "Friedrich Nietzsche", eraLabel: "近代", yearsLabel: "1844–1900", oneLiner: "価値の再評価を迫り、近代道徳を挑発した。", quote: "神は死んだ。", coreQuestion: "既存の価値は誰のためのものか。", basicAnswer: "価値は生成されるもので、再創造されるべき。", opposedTo: "カント的普遍道徳", epistemology: "遠近法主義。", viewOfHuman: "自己超克する力への意志。", ethicalPoliticalImplication: "道徳の系譜批判と個の創造性。", laterInfluence: "実存主義、ポスト構造主義。", keyConcepts: ["力への意志", "永劫回帰", "価値転換"], keyWorks: ["善悪の彼岸", "ツァラトゥストラ"], relatedThemeSlugs: ["happiness", "freedom"], relatedThinkerSlugs: ["kant", "sartre"], relatedComparisonSlugs: ["kant-nietzsche"] },
  { slug: "sartre", nameJa: "サルトル", nameEn: "Jean-Paul Sartre", eraLabel: "現代", yearsLabel: "1905–1980", oneLiner: "実存の自由と責任を徹底した。", quote: "実存は本質に先立つ。", coreQuestion: "自由はなぜ重荷になるのか。", basicAnswer: "人間は自己選択の責任から逃れられない。", opposedTo: "本質主義", epistemology: "現象学的分析。", viewOfHuman: "投企する自由な存在。", ethicalPoliticalImplication: "他者と関係しつつ責任を負う倫理。", laterInfluence: "実存主義、文学、政治運動。", keyConcepts: ["自由", "悪い信仰", "実存"], keyWorks: ["存在と無", "実存主義とは何か"], relatedThemeSlugs: ["freedom", "death"], relatedThinkerSlugs: ["nietzsche", "heidegger"], relatedComparisonSlugs: ["nietzsche-sartre"] },
  { slug: "confucius", nameJa: "孔子", nameEn: "Confucius", eraLabel: "古代中国", yearsLabel: "551–479 BCE", oneLiner: "関係性の倫理から秩序を築く。", quote: "仁者は人を愛す。", coreQuestion: "よい社会はどう育つか。", basicAnswer: "礼と仁を実践する人格形成が基盤となる。", opposedTo: "法家の強制秩序", epistemology: "古典学習と実践知。", viewOfHuman: "修養によって徳を高めうる。", ethicalPoliticalImplication: "徳治と家族・共同体倫理。", laterInfluence: "東アジア政治文化と教育観。", keyConcepts: ["仁", "礼", "君子"], keyWorks: ["論語"], relatedThemeSlugs: ["justice", "happiness"], relatedThinkerSlugs: ["mencius", "xunzi"], relatedComparisonSlugs: ["confucius-laozi"] },
  { slug: "laozi", nameJa: "老子", nameEn: "Laozi", eraLabel: "古代中国", yearsLabel: "6th–5th c. BCE", oneLiner: "無為自然で人為の過剰を戒めた。", quote: "為無為、事無事。", coreQuestion: "秩序は統制でなく生まれるか。", basicAnswer: "作為を減らし道に従うことで調和する。", opposedTo: "儒家的な規範中心主義", epistemology: "言語化を超える直観知。", viewOfHuman: "自然の流れに沿う存在。", ethicalPoliticalImplication: "小国寡民的な非干渉志向。", laterInfluence: "道教思想、東アジア美学。", keyConcepts: ["道", "無為", "柔弱"], keyWorks: ["道徳経"], relatedThemeSlugs: ["happiness", "language"], relatedThinkerSlugs: ["confucius", "zhuangzi"], relatedComparisonSlugs: ["confucius-laozi"] },
  { slug: "wittgenstein", nameJa: "ウィトゲンシュタイン", nameEn: "Ludwig Wittgenstein", eraLabel: "現代", yearsLabel: "1889–1951", oneLiner: "言語の限界と使用を哲学の核心に置いた。", quote: "語りえぬものについては沈黙しなければならない。", coreQuestion: "哲学的混乱はどこから生まれるか。", basicAnswer: "言語の誤用と文脈無視から生まれる。", opposedTo: "形而上学的言語観", epistemology: "論理像理論から言語ゲームへ転回。", viewOfHuman: "生活形式の中で意味を作る存在。", ethicalPoliticalImplication: "哲学を治療的実践へ。", laterInfluence: "分析哲学、言語論的転回。", keyConcepts: ["言語ゲーム", "家族的類似", "沈黙"], keyWorks: ["論理哲学論考", "哲学探究"], relatedThemeSlugs: ["language", "knowledge"], relatedThinkerSlugs: ["heidegger", "austin"], relatedComparisonSlugs: ["descartes-hume"] },
];
