import { Thinker } from "@/types/content";

export const thinkers: Thinker[] = [
  {
    slug: "plato",
    nameJa: "プラトン",
    nameEn: "Plato",
    eraLabel: "古代ギリシア",
    yearsLabel: "c. 427–347 BCE",
    oneLiner: "変わらない真理の世界を想定し、現実を読み解いた。",
    quote: "哲学とは死の練習である。",
    coreQuestion: "変化する世界の背後に普遍はあるか。",
    basicAnswer: "感覚世界の背後にイデアという真の実在がある。",
    opposedTo: "アリストテレスの実体論",
    epistemology: "想起説と弁証法で普遍知へ到達する。",
    viewOfHuman: "魂は理性的秩序へ向かう存在。",
    ethicalPoliticalImplication: "徳と統治は知に基づくべきだ。",
    laterInfluence: "新プラトン主義、キリスト教神学、観念論に影響。",
    keyConcepts: ["イデア", "魂", "哲人王"],
    keyWorks: ["国家", "饗宴", "パイドン"],
    relatedThemeSlugs: ["knowledge", "truth", "justice", "happiness", "human-nature"],
    relatedThinkerSlugs: ["aristotle", "epicurus", "zeno"],
    relatedComparisonSlugs: ["plato-aristotle", "plato-epicurus"],
  },
  {
    slug: "aristotle",
    nameJa: "アリストテレス",
    nameEn: "Aristotle",
    eraLabel: "古代ギリシア",
    yearsLabel: "384–322 BCE",
    oneLiner: "観察と分類から世界の秩序を記述した。",
    quote: "人間はポリス的動物である。",
    coreQuestion: "ものごとの本質はどこに宿るか。",
    basicAnswer: "本質は個物の内にある実体として理解できる。",
    opposedTo: "プラトンのイデア論",
    epistemology: "経験から普遍を抽出する。",
    viewOfHuman: "理性と実践を通じ徳を形成する存在。",
    ethicalPoliticalImplication: "中庸と共同体倫理が重要。",
    laterInfluence: "中世スコラ学から近代科学の方法論まで接続。",
    keyConcepts: ["実体", "四原因", "中庸"],
    keyWorks: ["形而上学", "ニコマコス倫理学", "政治学"],
    relatedThemeSlugs: ["knowledge", "truth", "happiness", "human-nature"],
    relatedThinkerSlugs: ["plato", "zeno", "epictetus"],
    relatedComparisonSlugs: ["plato-aristotle", "aristotle-stoicism"],
  },
  {
    slug: "epicurus",
    nameJa: "エピクロス",
    nameEn: "Epicurus",
    eraLabel: "古代ギリシア",
    yearsLabel: "341–270 BCE",
    oneLiner: "不安を減らす静かな快を、よく生きる軸に置いた。",
    quote: "快楽こそ、幸福な生の始まりであり終わりである。",
    coreQuestion: "善く生きるには何を減らし、何を選ぶべきか。",
    basicAnswer: "過剰欲望と死の恐怖を退け、節度ある快で心の平静を保つ。",
    opposedTo: "禁欲を絶対化する倫理観",
    epistemology: "感覚と経験に基づく自然主義。",
    viewOfHuman: "有限な欲望を調整できる感覚的理性的存在。",
    ethicalPoliticalImplication: "政治的名誉より日常の友愛と節制を重視。",
    laterInfluence: "快楽主義、近代経験論、世俗的幸福論に影響。",
    keyConcepts: ["アタラクシア", "快楽", "欲望の分類"],
    keyWorks: ["メノイケウス宛書簡", "主要教説"],
    relatedThemeSlugs: ["happiness", "freedom", "human-nature"],
    relatedThinkerSlugs: ["plato", "zeno", "epictetus"],
    relatedComparisonSlugs: ["stoicism-epicureanism", "plato-epicurus", "epictetus-epicurus"],
  },
  {
    slug: "zeno",
    nameJa: "ゼノン",
    nameEn: "Zeno of Citium",
    eraLabel: "古代ギリシア",
    yearsLabel: "c. 334–262 BCE",
    oneLiner: "自然に即した理性の生を、ストア派の出発点にした。",
    quote: "自然に従って生きよ。",
    coreQuestion: "外的変動に揺れずに善く生きる基準は何か。",
    basicAnswer: "徳だけが真の善であり、理性に沿う生が自由をもたらす。",
    opposedTo: "快楽を最高善に置く立場",
    epistemology: "宇宙理性への同意を重視する理性主義。",
    viewOfHuman: "全体秩序の一部として理性を分有する存在。",
    ethicalPoliticalImplication: "徳を核にした普遍的共同体意識を促す。",
    laterInfluence: "ローマ・ストア派、自然法思想、近代徳倫理に波及。",
    keyConcepts: ["自然に従う", "徳", "アパテイア"],
    keyWorks: ["国家（断片）", "自然について（断片）"],
    relatedThemeSlugs: ["happiness", "freedom", "human-nature"],
    relatedThinkerSlugs: ["epicurus", "aristotle", "epictetus", "marcus-aurelius"],
    relatedComparisonSlugs: ["stoicism-epicureanism", "aristotle-stoicism"],
  },
  {
    slug: "epictetus",
    nameJa: "エピクテトス",
    nameEn: "Epictetus",
    eraLabel: "古代ローマ",
    yearsLabel: "c. 50–135 CE",
    oneLiner: "自分で統御できるものに集中する実践倫理を示した。",
    quote: "あなたを乱すのは事柄ではなく、事柄についての判断である。",
    coreQuestion: "不運や不安の中でどう内面の自由を保つか。",
    basicAnswer: "統御可能と不可能を区別し、判断と意志を鍛える。",
    opposedTo: "外的成功を幸福の中心に置く生き方",
    epistemology: "日常訓練を通じた実践的理性。",
    viewOfHuman: "判断を鍛えることで自由になれる存在。",
    ethicalPoliticalImplication: "境遇を超えて責任と自律を確保する倫理。",
    laterInfluence: "自己啓発的倫理、実践哲学、心理療法的発想に影響。",
    keyConcepts: ["統御可能性", "プロハイレシス", "訓練"],
    keyWorks: ["語録", "提要"],
    relatedThemeSlugs: ["happiness", "freedom", "human-nature"],
    relatedThinkerSlugs: ["zeno", "marcus-aurelius", "epicurus"],
    relatedComparisonSlugs: ["epictetus-epicurus", "marcus-epictetus", "aristotle-stoicism"],
  },
  {
    slug: "marcus-aurelius",
    nameJa: "マルクス・アウレリウス",
    nameEn: "Marcus Aurelius",
    eraLabel: "古代ローマ",
    yearsLabel: "121–180 CE",
    oneLiner: "権力の只中で、内面の統御を続けるストア的実践を残した。",
    quote: "あなたの心は、あなたの支配のもとにある。",
    coreQuestion: "重い責務の中で平静と徳をどう維持するか。",
    basicAnswer: "自然の秩序を受け入れつつ、判断と行為を徳に合わせ続ける。",
    opposedTo: "名誉や快楽への過度な執着",
    epistemology: "自己省察と反復訓練による実践知。",
    viewOfHuman: "共同体への責任を担う理性的存在。",
    ethicalPoliticalImplication: "公的責任と内面の自由を両立させる統治倫理。",
    laterInfluence: "ストア主義受容、リーダーシップ論、実践的倫理教育に影響。",
    keyConcepts: ["自己省察", "受容", "宇宙市民"],
    keyWorks: ["自省録"],
    relatedThemeSlugs: ["happiness", "freedom", "human-nature"],
    relatedThinkerSlugs: ["epictetus", "zeno", "aristotle"],
    relatedComparisonSlugs: ["marcus-epictetus", "stoicism-epicureanism"],
  },
  {
    slug: "descartes",
    nameJa: "デカルト",
    nameEn: "René Descartes",
    eraLabel: "近代",
    yearsLabel: "1596–1650",
    oneLiner: "方法的懐疑で確実性を探した。",
    quote: "我思う、ゆえに我あり。",
    coreQuestion: "疑い得ない知の出発点は何か。",
    basicAnswer: "思考する自我の確実性が基礎になる。",
    opposedTo: "ヒュームの経験論的懐疑",
    epistemology: "生得観念と演繹理性を重視。",
    viewOfHuman: "心身二元論で理性的主体を中心化。",
    ethicalPoliticalImplication: "普遍的理性への信頼を強化。",
    laterInfluence: "合理主義と近代主体概念の土台。",
    keyConcepts: ["方法的懐疑", "コギト", "心身二元論"],
    keyWorks: ["方法序説", "省察"],
    relatedThemeSlugs: ["knowledge", "truth", "language"],
    relatedThinkerSlugs: ["spinoza", "locke", "hume", "kant"],
    relatedComparisonSlugs: ["descartes-hume", "descartes-locke", "spinoza-descartes"],
  },
  {
    slug: "locke",
    nameJa: "ロック",
    nameEn: "John Locke",
    eraLabel: "近代",
    yearsLabel: "1632–1704",
    oneLiner: "経験を起点に、知識の範囲と限界を描いた。",
    quote: "精神は白紙として始まる。",
    coreQuestion: "人間の知識はどこから来るのか。",
    basicAnswer: "観念は経験から形成され、知識はその結合の把握である。",
    opposedTo: "デカルトやライプニッツの生得観念説",
    epistemology: "経験論、観念分析、知識の範囲限定。",
    viewOfHuman: "経験で形成される理性的かつ可塑的な存在。",
    ethicalPoliticalImplication: "寛容と統治正当化の経験的基盤を支える。",
    laterInfluence: "英経験論、近代自由主義、教育思想へ影響。",
    keyConcepts: ["タブラ・ラサ", "一次性質/二次性質", "観念"],
    keyWorks: ["人間知性論", "統治二論"],
    relatedThemeSlugs: ["knowledge", "truth", "justice", "freedom", "state-legitimacy"],
    relatedThinkerSlugs: ["descartes", "hume", "leibniz", "berkeley", "hobbes", "rousseau"],
    relatedComparisonSlugs: ["descartes-locke", "leibniz-locke", "locke-hume", "berkeley-locke", "hobbes-locke", "locke-rousseau"],
  },
  {
    slug: "spinoza",
    nameJa: "スピノザ",
    nameEn: "Baruch Spinoza",
    eraLabel: "近代",
    yearsLabel: "1632–1677",
    oneLiner: "神即自然の一元論で、理性の徹底を図った。",
    quote: "神とは、すなわち自然である。",
    coreQuestion: "自由は必然の世界でどう可能か。",
    basicAnswer: "必然を理性で理解するほど受動から能動へ移れる。",
    opposedTo: "デカルトの心身二元論",
    epistemology: "公理的演繹と直観知を重視する合理論。",
    viewOfHuman: "自然の一様態として因果網の中にある存在。",
    ethicalPoliticalImplication: "感情統御と寛容政治の理論へ接続。",
    laterInfluence: "ドイツ観念論、現代政治哲学、感情論に波及。",
    keyConcepts: ["神即自然", "実体一元論", "コナトゥス"],
    keyWorks: ["エチカ", "神学政治論"],
    relatedThemeSlugs: ["knowledge", "truth", "freedom"],
    relatedThinkerSlugs: ["descartes", "leibniz", "kant"],
    relatedComparisonSlugs: ["spinoza-descartes"],
  },
  {
    slug: "leibniz",
    nameJa: "ライプニッツ",
    nameEn: "G. W. Leibniz",
    eraLabel: "近代",
    yearsLabel: "1646–1716",
    oneLiner: "生得的秩序と論理で経験を組み替えた。",
    quote: "精神の中には、経験の前から多くがある。",
    coreQuestion: "経験以前に認識を支える構造はあるか。",
    basicAnswer: "モナドと生得的原理が知識の可能性を支える。",
    opposedTo: "ロックの白紙説",
    epistemology: "合理主義、真理の二分類、十分理由律。",
    viewOfHuman: "内的原理で世界を表象する能動的精神。",
    ethicalPoliticalImplication: "調和モデルによる理性中心の秩序観。",
    laterInfluence: "論理学、数学、ドイツ哲学への橋渡し。",
    keyConcepts: ["モナド", "十分理由律", "真理の二分類"],
    keyWorks: ["人間知性新論", "モナドロジー"],
    relatedThemeSlugs: ["knowledge", "truth"],
    relatedThinkerSlugs: ["locke", "descartes", "kant"],
    relatedComparisonSlugs: ["leibniz-locke"],
  },
  {
    slug: "berkeley",
    nameJa: "バークリー",
    nameEn: "George Berkeley",
    eraLabel: "近代",
    yearsLabel: "1685–1753",
    oneLiner: "知覚されることを存在条件にして実体観を削った。",
    quote: "存在するとは知覚されることである。",
    coreQuestion: "物質実体なしに経験世界は成り立つか。",
    basicAnswer: "観念と精神の関係だけで世界説明は可能である。",
    opposedTo: "ロックの物質実体仮説",
    epistemology: "経験論を観念論へ押し進める。",
    viewOfHuman: "知覚と意志をもつ精神的主体。",
    ethicalPoliticalImplication: "常識的信仰と道徳秩序の擁護へ向かう。",
    laterInfluence: "ヒュームの懐疑、観念論的伝統を刺激。",
    keyConcepts: ["存在するとは知覚されること", "非物質主義", "観念"],
    keyWorks: ["人知原理論", "ハイラスとフィロナスの三対話"],
    relatedThemeSlugs: ["knowledge", "truth"],
    relatedThinkerSlugs: ["locke", "hume", "kant"],
    relatedComparisonSlugs: ["berkeley-locke", "locke-hume"],
  },
  {
    slug: "hume",
    nameJa: "ヒューム",
    nameEn: "David Hume",
    eraLabel: "近代",
    yearsLabel: "1711–1776",
    oneLiner: "経験の限界を徹底し、因果と自我を問い直した。",
    quote: "理性は情念の奴隷である。",
    coreQuestion: "私たちは何を正当化できるのか。",
    basicAnswer: "確実性ではなく習慣と蓋然性が認識を支える。",
    opposedTo: "デカルト的合理主義",
    epistemology: "印象と観念、懐疑的経験論。",
    viewOfHuman: "理性より情念と習慣に導かれる。",
    ethicalPoliticalImplication: "道徳感情と慣習の役割を重視。",
    laterInfluence: "カントの批判哲学を刺激。",
    keyConcepts: ["因果の習慣説", "束としての自我", "帰納問題"],
    keyWorks: ["人間本性論", "人間知性研究"],
    relatedThemeSlugs: ["knowledge", "truth", "freedom"],
    relatedThinkerSlugs: ["locke", "berkeley", "descartes", "kant"],
    relatedComparisonSlugs: ["locke-hume", "berkeley-locke", "descartes-hume", "hume-kant"],
  },
  {
    slug: "kant",
    nameJa: "カント",
    nameEn: "Immanuel Kant",
    eraLabel: "近代",
    yearsLabel: "1724–1804",
    oneLiner: "経験と理性の条件を批判的に統合した。",
    quote: "啓蒙とは、人間が未成年状態から抜け出すこと。",
    coreQuestion: "経験が成立する条件は何か。",
    basicAnswer: "主体の先験的形式が経験を可能にする。",
    opposedTo: "経験論と独断的合理論の双方",
    epistemology: "先験論的観念論。",
    viewOfHuman: "自律的に法を立てる理性的存在。",
    ethicalPoliticalImplication: "人格の尊厳と義務倫理。",
    laterInfluence: "ドイツ観念論、現代倫理学に巨大な影響。",
    keyConcepts: ["先験的", "定言命法", "物自体"],
    keyWorks: ["純粋理性批判", "実践理性批判"],
    relatedThemeSlugs: ["knowledge", "truth", "freedom", "justice", "happiness"],
    relatedThinkerSlugs: ["hume", "locke", "bentham", "mill", "nietzsche"],
    relatedComparisonSlugs: ["hume-kant", "kant-bentham", "kant-nietzsche"],
  },
  {
    slug: "bentham",
    nameJa: "ベンサム",
    nameEn: "Jeremy Bentham",
    eraLabel: "近代",
    yearsLabel: "1748–1832",
    oneLiner: "快苦の計算で制度と行為を評価した。",
    quote: "最大多数の最大幸福。",
    coreQuestion: "善い行為や制度をどう判定するか。",
    basicAnswer: "結果として生まれる効用の総量で判定すべきだ。",
    opposedTo: "カントの義務論",
    epistemology: "経験的観察に基づく帰結評価。",
    viewOfHuman: "快楽と苦痛に反応する存在。",
    ethicalPoliticalImplication: "立法・刑罰・行政を効用最大化で再設計する。",
    laterInfluence: "功利主義、法哲学、政策評価手法に影響。",
    keyConcepts: ["効用", "快苦計算", "最大多数の最大幸福"],
    keyWorks: ["道徳および立法の諸原理序説"],
    relatedThemeSlugs: ["happiness", "justice", "state-legitimacy"],
    relatedThinkerSlugs: ["kant", "mill", "rawls"],
    relatedComparisonSlugs: ["kant-bentham", "bentham-mill"],
  },
  {
    slug: "mill",
    nameJa: "J.S.ミル",
    nameEn: "John Stuart Mill",
    eraLabel: "近代",
    yearsLabel: "1806–1873",
    oneLiner: "功利主義を自由と人格形成の理論へ拡張した。",
    quote: "他者危害を防ぐ場合を除き、自由は尊重されるべきだ。",
    coreQuestion: "幸福と自由はどう両立できるか。",
    basicAnswer: "質的差異を認めた効用論と自由原理で両立させる。",
    opposedTo: "画一的な快楽量だけを見る功利主義",
    epistemology: "経験論と社会科学的検証を重視。",
    viewOfHuman: "能力開発でより高次の快を求める存在。",
    ethicalPoliticalImplication: "言論・生活様式の自由を制度の核に置く。",
    laterInfluence: "自由主義、女性解放論、現代公共哲学に波及。",
    keyConcepts: ["危害原理", "質的功利主義", "個性"],
    keyWorks: ["自由論", "功利主義論"],
    relatedThemeSlugs: ["freedom", "happiness", "justice", "state-legitimacy"],
    relatedThinkerSlugs: ["bentham", "kant", "rawls", "rousseau"],
    relatedComparisonSlugs: ["bentham-mill", "kant-bentham"],
  },
  {
    slug: "rawls",
    nameJa: "ロールズ",
    nameEn: "John Rawls",
    eraLabel: "現代",
    yearsLabel: "1921–2002",
    oneLiner: "公正としての正義で自由と平等の再配列を示した。",
    quote: "正義は社会制度の第一徳である。",
    coreQuestion: "自由な社会で不平等はいつ正当化されるか。",
    basicAnswer: "無知のヴェール下で合意できる原理のみが正当化される。",
    opposedTo: "結果のみで正当化する功利主義",
    epistemology: "反省的均衡と契約論的思考実験。",
    viewOfHuman: "互いに自由で平等な協働主体。",
    ethicalPoliticalImplication: "基本的自由の優先と格差原理を制度設計に要求。",
    laterInfluence: "現代政治哲学、再分配論、グローバル正義論に影響。",
    keyConcepts: ["無知のヴェール", "正義の二原理", "反省的均衡"],
    keyWorks: ["正義論", "政治的リベラリズム"],
    relatedThemeSlugs: ["justice", "freedom", "state-legitimacy"],
    relatedThinkerSlugs: ["marx", "mill", "kant", "rousseau"],
    relatedComparisonSlugs: ["rawls-marx"],
  },
  {
    slug: "marx",
    nameJa: "マルクス",
    nameEn: "Karl Marx",
    eraLabel: "近代",
    yearsLabel: "1818–1883",
    oneLiner: "生産関係と階級闘争から社会秩序を批判した。",
    quote: "哲学者たちは世界を解釈してきたにすぎない。重要なのは変革することだ。",
    coreQuestion: "資本主義社会の不平等はなぜ再生産されるか。",
    basicAnswer: "私的所有と搾取構造が疎外と階級支配を生む。",
    opposedTo: "形式的平等で十分とする自由主義",
    epistemology: "史的唯物論とイデオロギー批判。",
    viewOfHuman: "労働を通じ自己形成する社会的存在。",
    ethicalPoliticalImplication: "所有関係の転換と階級支配の克服を求める。",
    laterInfluence: "労働運動、批判理論、社会科学に巨大な影響。",
    keyConcepts: ["階級闘争", "疎外", "史的唯物論"],
    keyWorks: ["資本論", "共産党宣言"],
    relatedThemeSlugs: ["justice", "freedom", "state-legitimacy"],
    relatedThinkerSlugs: ["rawls", "rousseau", "hobbes"],
    relatedComparisonSlugs: ["rawls-marx"],
  },
  {
    slug: "rousseau",
    nameJa: "ルソー",
    nameEn: "Jean-Jacques Rousseau",
    eraLabel: "近代",
    yearsLabel: "1712–1778",
    oneLiner: "自由と共同体を一般意志で再定義した。",
    quote: "人間は自由なものとして生まれ、至るところで鎖につながれている。",
    coreQuestion: "自由は共同体でどう守られるか。",
    basicAnswer: "一般意志への参与で市民的自由を実現する。",
    opposedTo: "ホッブズ的統治観",
    epistemology: "文明批判と道徳感情。",
    viewOfHuman: "本性的善性を持つが社会で歪む。",
    ethicalPoliticalImplication: "民主主義理論へ影響。",
    laterInfluence: "革命思想、教育論、ロマン主義。",
    keyConcepts: ["一般意志", "社会契約", "市民教育"],
    keyWorks: ["社会契約論", "エミール"],
    relatedThemeSlugs: ["freedom", "justice", "state-legitimacy"],
    relatedThinkerSlugs: ["hobbes", "locke", "mill", "rawls"],
    relatedComparisonSlugs: ["hobbes-rousseau", "locke-rousseau"],
  },
  {
    slug: "hobbes",
    nameJa: "ホッブズ",
    nameEn: "Thomas Hobbes",
    eraLabel: "近代",
    yearsLabel: "1588–1679",
    oneLiner: "秩序維持のため主権国家を理論化した。",
    quote: "万人の万人に対する闘争。",
    coreQuestion: "なぜ国家が必要か。",
    basicAnswer: "自然状態の不安を避けるため契約で主権を立てる。",
    opposedTo: "ルソーの一般意志中心の契約",
    epistemology: "機械論的自然観。",
    viewOfHuman: "自己保存を優先する存在。",
    ethicalPoliticalImplication: "強い主権と秩序を正当化。",
    laterInfluence: "近代国家論と政治的リアリズム。",
    keyConcepts: ["自然状態", "契約", "リヴァイアサン"],
    keyWorks: ["リヴァイアサン"],
    relatedThemeSlugs: ["freedom", "justice", "state-legitimacy"],
    relatedThinkerSlugs: ["rousseau", "locke", "marx"],
    relatedComparisonSlugs: ["hobbes-rousseau", "hobbes-locke"],
  },
  {
    slug: "nietzsche",
    nameJa: "ニーチェ",
    nameEn: "Friedrich Nietzsche",
    eraLabel: "近代",
    yearsLabel: "1844–1900",
    oneLiner: "価値の再評価を迫り、近代道徳を挑発した。",
    quote: "神は死んだ。",
    coreQuestion: "既存の価値は誰のためのものか。",
    basicAnswer: "価値は生成されるもので、再創造されるべき。",
    opposedTo: "カント的普遍道徳",
    epistemology: "遠近法主義。",
    viewOfHuman: "自己超克する力への意志。",
    ethicalPoliticalImplication: "道徳の系譜批判と個の創造性。",
    laterInfluence: "実存主義、ポスト構造主義。",
    keyConcepts: ["力への意志", "永劫回帰", "価値転換"],
    keyWorks: ["善悪の彼岸", "ツァラトゥストラ"],
    relatedThemeSlugs: ["happiness", "freedom"],
    relatedThinkerSlugs: ["kant", "sartre"],
    relatedComparisonSlugs: ["kant-nietzsche"],
  },
  {
    slug: "sartre",
    nameJa: "サルトル",
    nameEn: "Jean-Paul Sartre",
    eraLabel: "現代",
    yearsLabel: "1905–1980",
    oneLiner: "実存の自由と責任を徹底した。",
    quote: "実存は本質に先立つ。",
    coreQuestion: "自由はなぜ重荷になるのか。",
    basicAnswer: "人間は自己選択の責任から逃れられない。",
    opposedTo: "本質主義",
    epistemology: "現象学的分析。",
    viewOfHuman: "投企する自由な存在。",
    ethicalPoliticalImplication: "他者と関係しつつ責任を負う倫理。",
    laterInfluence: "実存主義、文学、政治運動。",
    keyConcepts: ["自由", "悪い信仰", "実存"],
    keyWorks: ["存在と無", "実存主義とは何か"],
    relatedThemeSlugs: ["freedom", "death"],
    relatedThinkerSlugs: ["nietzsche", "kant"],
    relatedComparisonSlugs: ["nietzsche-sartre"],
  },
  {
    slug: "confucius",
    nameJa: "孔子",
    nameEn: "Confucius",
    eraLabel: "古代中国",
    yearsLabel: "551–479 BCE",
    oneLiner: "関係性の倫理から秩序を築く。",
    quote: "仁者は人を愛す。",
    coreQuestion: "よい社会はどう育つか。",
    basicAnswer: "礼と仁を実践する人格形成が基盤となる。",
    opposedTo: "法家の強制秩序",
    epistemology: "古典学習と実践知。",
    viewOfHuman: "修養によって徳を高めうる。",
    ethicalPoliticalImplication: "徳治と家族・共同体倫理。",
    laterInfluence: "東アジア政治文化と教育観。",
    keyConcepts: ["仁", "礼", "君子"],
    keyWorks: ["論語"],
    relatedThemeSlugs: ["justice", "happiness"],
    relatedThinkerSlugs: ["laozi", "plato"],
    relatedComparisonSlugs: ["confucius-laozi"],
  },
  {
    slug: "laozi",
    nameJa: "老子",
    nameEn: "Laozi",
    eraLabel: "古代中国",
    yearsLabel: "6th–5th c. BCE",
    oneLiner: "無為自然で人為の過剰を戒めた。",
    quote: "為無為、事無事。",
    coreQuestion: "秩序は統制でなく生まれるか。",
    basicAnswer: "作為を減らし道に従うことで調和する。",
    opposedTo: "儒家的な規範中心主義",
    epistemology: "言語化を超える直観知。",
    viewOfHuman: "自然の流れに沿う存在。",
    ethicalPoliticalImplication: "小国寡民的な非干渉志向。",
    laterInfluence: "道教思想、東アジア美学。",
    keyConcepts: ["道", "無為", "柔弱"],
    keyWorks: ["道徳経"],
    relatedThemeSlugs: ["happiness", "language"],
    relatedThinkerSlugs: ["confucius", "wittgenstein"],
    relatedComparisonSlugs: ["confucius-laozi"],
  },
  {
    slug: "wittgenstein",
    nameJa: "ウィトゲンシュタイン",
    nameEn: "Ludwig Wittgenstein",
    eraLabel: "現代",
    yearsLabel: "1889–1951",
    oneLiner: "言語の限界と使用を哲学の核心に置いた。",
    quote: "語りえぬものについては沈黙しなければならない。",
    coreQuestion: "哲学的混乱はどこから生まれるか。",
    basicAnswer: "言語の誤用と文脈無視から生まれる。",
    opposedTo: "形而上学的言語観",
    epistemology: "論理像理論から言語ゲームへ転回。",
    viewOfHuman: "生活形式の中で意味を作る存在。",
    ethicalPoliticalImplication: "哲学を治療的実践へ。",
    laterInfluence: "分析哲学、言語論的転回。",
    keyConcepts: ["言語ゲーム", "家族的類似", "沈黙"],
    keyWorks: ["論理哲学論考", "哲学探究"],
    relatedThemeSlugs: ["language", "knowledge", "truth"],
    relatedThinkerSlugs: ["descartes", "kant"],
    relatedComparisonSlugs: ["descartes-hume"],
  },
];
